schema = 1

[meta]
name = "Harp 2"
author = "Vulpus Labs"
category = "Pluck"
comment = "Translated from DX7 factory ROM 'HARP    2': algo 3, feedback 6."

[params]
algo = 3
feedback = 4.2

# op1
op1-num = 1
op1-detune = 4
op1-level = 99
op1-vel-sens = 7
op1-eg-r1 = 95
op1-eg-r2 = 32
op1-eg-r3 = 45
op1-eg-r4 = 31
op1-eg-l1 = 99
op1-eg-l2 = 70
op1-eg-l3 = 0
op1-eg-l4 = 0
op1-ks-rate = 3
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 2
op2-detune = -1
op2-level = 79
op2-vel-sens = 3
op2-eg-r1 = 95
op2-eg-r2 = 46
op2-eg-r3 = 99
op2-eg-r4 = 12
op2-eg-l1 = 99
op2-eg-l2 = 70
op2-eg-l3 = 0
op2-eg-l4 = 0
op2-ks-rate = 3
op2-ks-break-pt = 73
op2-ks-l-depth = 8
op2-ks-r-depth = 0
op2-ks-l-curve = "pos-lin"

# op3
op3-num = 3
op3-detune = -4
op3-level = 62
op3-vel-sens = 0
op3-eg-r1 = 95
op3-eg-r2 = 50
op3-eg-r3 = 44
op3-eg-r4 = 10
op3-eg-l1 = 99
op3-eg-l2 = 70
op3-eg-l3 = 0
op3-eg-l4 = 0
op3-ks-rate = 3
op3-ks-break-pt = 79
op3-ks-l-depth = 0
op3-ks-r-depth = 37
op3-ks-r-curve = "neg-lin"

# op4
op4-num = 1
op4-detune = -3
op4-level = 99
op4-vel-sens = 7
op4-eg-r1 = 95
op4-eg-r2 = 32
op4-eg-r3 = 49
op4-eg-r4 = 33
op4-eg-l1 = 99
op4-eg-l2 = 70
op4-eg-l3 = 0
op4-eg-l4 = 0
op4-ks-rate = 3
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 3
op5-detune = 3
op5-level = 79
op5-vel-sens = 4
op5-eg-r1 = 95
op5-eg-r2 = 35
op5-eg-r3 = 99
op5-eg-r4 = 28
op5-eg-l1 = 99
op5-eg-l2 = 70
op5-eg-l3 = 0
op5-eg-l4 = 0
op5-ks-rate = 4
op5-ks-break-pt = 73
op5-ks-l-depth = 0
op5-ks-r-depth = 35
op5-ks-r-curve = "neg-lin"

# op6
op6-num = 3
op6-detune = -5
op6-level = 90
op6-vel-sens = 6
op6-eg-r1 = 95
op6-eg-r2 = 46
op6-eg-r3 = 28
op6-eg-r4 = 24
op6-eg-l1 = 94
op6-eg-l2 = 79
op6-eg-l3 = 0
op6-eg-l4 = 0
op6-ks-rate = 7
op6-ks-l-depth = 0
op6-ks-r-depth = 0

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -17.60
