schema = 1

[meta]
name = "Sitar"
author = "Vulpus Labs"
category = "Pluck"
comment = "Translated from DX7 factory ROM 'SITAR': algo 8, feedback 0."

[params]
algo = 8

# op1
op1-num = 20
op1-level = 73
op1-vel-sens = 1
op1-eg-r1 = 99
op1-eg-r2 = 77
op1-eg-r3 = 26
op1-eg-r4 = 42
op1-eg-l1 = 99
op1-eg-l2 = 98
op1-eg-l3 = 0
op1-eg-l4 = 0
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 1
op2-level = 97
op2-vel-sens = 2
op2-eg-r1 = 99
op2-eg-r2 = 41
op2-eg-r3 = 26
op2-eg-r4 = 7
op2-eg-l1 = 99
op2-eg-l2 = 98
op2-eg-l3 = 0
op2-eg-l4 = 0
op2-ks-l-depth = 0
op2-ks-r-depth = 0

# op3
op3-num = 1
op3-level = 91
op3-vel-sens = 2
op3-eg-r1 = 99
op3-eg-r2 = 77
op3-eg-r3 = 26
op3-eg-r4 = 28
op3-eg-l1 = 99
op3-eg-l2 = 98
op3-eg-l3 = 0
op3-eg-l4 = 0
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 7
op4-detune = -2
op4-level = 90
op4-vel-sens = 1
op4-eg-r1 = 99
op4-eg-r2 = 41
op4-eg-r3 = 42
op4-eg-r4 = 7
op4-eg-l1 = 99
op4-eg-l2 = 98
op4-eg-l3 = 0
op4-eg-l4 = 0
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 1
op5-detune = -4
op5-level = 87
op5-vel-sens = 2
op5-eg-r1 = 99
op5-eg-r2 = 77
op5-eg-r3 = 26
op5-eg-r4 = 7
op5-eg-l1 = 99
op5-eg-l2 = 98
op5-eg-l3 = 0
op5-eg-l4 = 0
op5-ks-l-depth = 0
op5-ks-r-depth = 0

# op6
op6-num = 9
op6-detune = 1
op6-level = 37
op6-vel-sens = 3
op6-eg-r1 = 99
op6-eg-r2 = 41
op6-eg-r3 = 26
op6-eg-r4 = 10
op6-eg-l1 = 99
op6-eg-l2 = 98
op6-eg-l3 = 0
op6-eg-l4 = 0
op6-ks-l-depth = 0
op6-ks-r-depth = 0

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -7.99
