schema = 1

[meta]
name = "Gong 2"
author = "Vulpus Labs"
category = "Bell"
comment = "Translated from DX7 factory ROM 'GONG    2': algo 17, feedback 7. DX7 transpose -12 st baked into ratios."

[params]
algo = 17
feedback = 4.9

# op1
op1-num = 1
op1-denom = 2
op1-level = 99
op1-vel-sens = 1
op1-eg-r1 = 79
op1-eg-r2 = 26
op1-eg-r3 = 20
op1-eg-r4 = 41
op1-eg-l1 = 99
op1-eg-l2 = 95
op1-eg-l3 = 41
op1-eg-l4 = 0
op1-ks-rate = 0
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 1
op2-denom = 2
op2-level = 56
op2-vel-sens = 2
op2-eg-r1 = 29
op2-eg-r2 = 42
op2-eg-r3 = 20
op2-eg-r4 = 18
op2-eg-l1 = 99
op2-eg-l2 = 85
op2-eg-l3 = 41
op2-eg-l4 = 0
op2-ks-rate = 1
op2-ks-l-depth = 0
op2-ks-r-depth = 0

# op3
op3-num = 9
op3-denom = 2
op3-fine = 24
op3-level = 63
op3-vel-sens = 1
op3-eg-r1 = 36
op3-eg-r2 = 30
op3-eg-r3 = 50
op3-eg-r4 = 24
op3-eg-l1 = 95
op3-eg-l2 = 87
op3-eg-l3 = 0
op3-eg-l4 = 0
op3-ks-rate = 0
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 2
op4-fine = -11
op4-level = 65
op4-vel-sens = 2
op4-eg-r1 = 79
op4-eg-r2 = 30
op4-eg-r3 = 15
op4-eg-r4 = 24
op4-eg-l1 = 95
op4-eg-l2 = 87
op4-eg-l3 = 0
op4-eg-l4 = 0
op4-ks-rate = 0
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 3
op5-fine = -20
op5-level = 67
op5-vel-sens = 7
op5-eg-r1 = 43
op5-eg-r2 = 30
op5-eg-r3 = 15
op5-eg-r4 = 10
op5-eg-l1 = 95
op5-eg-l2 = 87
op5-eg-l3 = 0
op5-eg-l4 = 0
op5-ks-rate = 0
op5-ks-l-depth = 0
op5-ks-r-depth = 0

# op6
op6-num = 7
op6-fine = 20
op6-level = 65
op6-vel-sens = 2
op6-eg-r1 = 40
op6-eg-r2 = 25
op6-eg-r3 = 7
op6-eg-r4 = 16
op6-eg-l1 = 86
op6-eg-l2 = 96
op6-eg-l3 = 0
op6-eg-l4 = 0
op6-ks-rate = 0
op6-ks-l-depth = 0
op6-ks-r-depth = 0

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -13.88
