schema = 1

[meta]
name = "Flute 1"
author = "Vulpus Labs"
category = "Wind"
comment = "Translated from DX7 factory ROM 'FLUTE   1': algo 16, feedback 5."

[params]
algo = 16
feedback = 3.5

# op1
op1-num = 1
op1-detune = -1
op1-level = 98
op1-vel-sens = 2
op1-eg-r1 = 61
op1-eg-r2 = 67
op1-eg-r3 = 70
op1-eg-r4 = 65
op1-eg-l1 = 93
op1-eg-l2 = 89
op1-eg-l3 = 98
op1-eg-l4 = 0
op1-ks-rate = 0
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 1
op2-detune = 3
op2-level = 75
op2-vel-sens = 2
op2-eg-r1 = 99
op2-eg-r2 = 97
op2-eg-r3 = 62
op2-eg-r4 = 54
op2-eg-l1 = 99
op2-eg-l2 = 99
op2-eg-l3 = 90
op2-eg-l4 = 0
op2-ks-rate = 4
op2-ks-l-depth = 0
op2-ks-r-depth = 0

# op3
op3-num = 1
op3-detune = -2
op3-level = 76
op3-vel-sens = 0
op3-eg-r1 = 53
op3-eg-r2 = 38
op3-eg-r3 = 75
op3-eg-r4 = 61
op3-eg-l1 = 88
op3-eg-l2 = 44
op3-eg-l3 = 24
op3-eg-l4 = 0
op3-ks-rate = 0
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 2
op4-level = 0
op4-vel-sens = 0
op4-eg-r1 = 61
op4-eg-r2 = 25
op4-eg-r3 = 25
op4-eg-r4 = 60
op4-eg-l1 = 99
op4-eg-l2 = 99
op4-eg-l3 = 97
op4-eg-l4 = 0
op4-ks-rate = 3
op4-ks-break-pt = 81
op4-ks-l-depth = 10
op4-ks-r-depth = 10
op4-ks-r-curve = "neg-lin"

# op5
op5-num = 2
op5-level = 56
op5-vel-sens = 0
op5-eg-r1 = 65
op5-eg-r2 = 38
op5-eg-r3 = 0
op5-eg-r4 = 61
op5-eg-l1 = 99
op5-eg-l2 = 0
op5-eg-l3 = 0
op5-eg-l4 = 0
op5-ks-rate = 0
op5-ks-break-pt = 74
op5-ks-l-depth = 0
op5-ks-r-depth = 43
op5-ks-r-curve = "neg-lin"

# op6
op6-num = 3
op6-denom = 2
op6-fine = 6
op6-detune = 3
op6-level = 83
op6-vel-sens = 2
op6-eg-r1 = 99
op6-eg-r2 = 64
op6-eg-r3 = 98
op6-eg-r4 = 61
op6-eg-l1 = 99
op6-eg-l2 = 67
op6-eg-l3 = 52
op6-eg-l4 = 0
op6-ks-rate = 0
op6-ks-l-depth = 0
op6-ks-r-depth = 0

lfo2-shape = "Tri"
lfo2-rate = 4.32
lfo2-delay = 216.0
lfo2-fade = 0.0

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -14.67

[[matrix]]
slot = 0
source = "lfo2"
dest = "global-pitch"
depth = 0.0032

[[matrix]]
slot = 1
source = "lfo2"
dest = "op3-level"
depth = 0.0131
