schema = 1

[meta]
name = "WHISTLES"
author = "Vulpus Labs"
category = "Wind"
comment = "Translated from DX7 factory ROM 'WHISTLES': algo 25, feedback 6."

[params]
algo = 25
feedback = 4.2

# op1
op1-num = 2
op1-level = 99
op1-vel-sens = 0
op1-eg-r1 = 45
op1-eg-r2 = 61
op1-eg-r3 = 65
op1-eg-r4 = 66
op1-eg-l1 = 65
op1-eg-l2 = 79
op1-eg-l3 = 99
op1-eg-l4 = 0
op1-ks-rate = 0
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 2
op2-level = 99
op2-vel-sens = 0
op2-eg-r1 = 45
op2-eg-r2 = 87
op2-eg-r3 = 65
op2-eg-r4 = 67
op2-eg-l1 = 65
op2-eg-l2 = 0
op2-eg-l3 = 99
op2-eg-l4 = 0
op2-ks-rate = 0
op2-ks-l-depth = 0
op2-ks-r-depth = 0

# op3
op3-num = 2
op3-detune = -5
op3-level = 99
op3-vel-sens = 0
op3-eg-r1 = 44
op3-eg-r2 = 70
op3-eg-r3 = 99
op3-eg-r4 = 82
op3-eg-l1 = 98
op3-eg-l2 = 0
op3-eg-l3 = 0
op3-eg-l4 = 0
op3-ks-rate = 0
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 1
op4-detune = 21
op4-level = 0
op4-vel-sens = 0
op4-eg-r1 = 99
op4-eg-r2 = 64
op4-eg-r3 = 23
op4-eg-r4 = 32
op4-eg-l1 = 99
op4-eg-l2 = 18
op4-eg-l3 = 17
op4-eg-l4 = 0
op4-ks-break-pt = 60
op4-ks-l-depth = 4
op4-ks-r-depth = 14
op4-ks-l-curve = "pos-exp"
op4-ks-r-curve = "neg-lin"

# op5
op5-num = 1
op5-fine = -50
op5-detune = 20
op5-level = 0
op5-vel-sens = 2
op5-eg-r1 = 99
op5-eg-r2 = 22
op5-eg-r3 = 23
op5-eg-r4 = 32
op5-eg-l1 = 99
op5-eg-l2 = 18
op5-eg-l3 = 17
op5-eg-l4 = 0
op5-ks-break-pt = 60
op5-ks-l-depth = 10
op5-ks-r-depth = 14
op5-ks-l-curve = "pos-exp"
op5-ks-r-curve = "neg-lin"

# op6
op6-num = 1
op6-fine = -50
op6-detune = 1
op6-level = 0
op6-vel-sens = 3
op6-eg-r1 = 99
op6-eg-r2 = 22
op6-eg-r3 = 23
op6-eg-r4 = 32
op6-eg-l1 = 99
op6-eg-l2 = 18
op6-eg-l3 = 17
op6-eg-l4 = 0
op6-ks-break-pt = 60
op6-ks-l-depth = 4
op6-ks-r-depth = 14
op6-ks-l-curve = "pos-exp"
op6-ks-r-curve = "neg-lin"

peg-r1 = 71
peg-r2 = 67
peg-r3 = 98
peg-r4 = 98
peg-l1 = -12
peg-l2 = -6
peg-l3 = 0
peg-l4 = 0

lfo2-shape = "Tri"
lfo2-rate = 4.91
lfo2-delay = 720.0
lfo2-fade = 0.0

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -16.8

[[matrix]]
slot = 0
source = "lfo2"
dest = "global-pitch"
depth = 0.0166

[[matrix]]
slot = 1
source = "lfo2"
dest = "op5-level"
depth = 0.203
