schema = 1

[meta]
name = "SYN-CLAV 1"
author = "Vulpus Labs"
category = "Keys"
comment = "Translated from DX7 factory ROM 'SYN-CLAV 1': algo 16, feedback 7. DX7 transpose -12 st baked into ratios."

[params]
algo = 16
feedback = 4.9

# op1
op1-num = 1
op1-denom = 2
op1-level = 99
op1-vel-sens = 1
op1-eg-r1 = 99
op1-eg-r2 = 37
op1-eg-r3 = 17
op1-eg-r4 = 71
op1-eg-l1 = 99
op1-eg-l2 = 70
op1-eg-l3 = 55
op1-eg-l4 = 0
op1-ks-rate = 0
op1-ks-break-pt = 48
op1-ks-l-depth = 50
op1-ks-r-depth = 0
op1-ks-l-curve = "pos-lin"

# op2
op2-num = 1
op2-level = 78
op2-vel-sens = 4
op2-eg-r1 = 99
op2-eg-r2 = 46
op2-eg-r3 = 17
op2-eg-r4 = 71
op2-eg-l1 = 99
op2-eg-l2 = 61
op2-eg-l3 = 45
op2-eg-l4 = 0
op2-ks-rate = 0
op2-ks-break-pt = 60
op2-ks-l-depth = 0
op2-ks-r-depth = 14
op2-ks-r-curve = "pos-lin"

# op3
op3-num = 3
op3-denom = 2
op3-level = 84
op3-vel-sens = 4
op3-eg-r1 = 99
op3-eg-r2 = 46
op3-eg-r3 = 17
op3-eg-r4 = 71
op3-eg-l1 = 99
op3-eg-l2 = 61
op3-eg-l3 = 45
op3-eg-l4 = 0
op3-ks-rate = 0
op3-ks-break-pt = 60
op3-ks-l-depth = 0
op3-ks-r-depth = 14
op3-ks-r-curve = "pos-lin"

# op4
op4-num = 6
op4-level = 55
op4-vel-sens = 0
op4-eg-r1 = 99
op4-eg-r2 = 38
op4-eg-r3 = 17
op4-eg-r4 = 71
op4-eg-l1 = 99
op4-eg-l2 = 70
op4-eg-l3 = 62
op4-eg-l4 = 0
op4-ks-rate = 0
op4-ks-break-pt = 60
op4-ks-l-depth = 0
op4-ks-r-depth = 14
op4-ks-r-curve = "pos-lin"

# op5
op5-num = 1
op5-denom = 2
op5-level = 44
op5-vel-sens = 4
op5-eg-r1 = 99
op5-eg-r2 = 46
op5-eg-r3 = 17
op5-eg-r4 = 71
op5-eg-l1 = 99
op5-eg-l2 = 61
op5-eg-l3 = 45
op5-eg-l4 = 0
op5-ks-rate = 0
op5-ks-break-pt = 60
op5-ks-l-depth = 0
op5-ks-r-depth = 14
op5-ks-r-curve = "pos-lin"

# op6
op6-num = 21
op6-denom = 2
op6-level = 80
op6-vel-sens = 0
op6-eg-r1 = 99
op6-eg-r2 = 46
op6-eg-r3 = 17
op6-eg-r4 = 71
op6-eg-l1 = 99
op6-eg-l2 = 61
op6-eg-l3 = 45
op6-eg-l4 = 0
op6-ks-rate = 0
op6-ks-break-pt = 60
op6-ks-l-depth = 4
op6-ks-r-depth = 55
op6-ks-l-curve = "pos-lin"
op6-ks-r-curve = "neg-lin"

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -3.0
