schema = 1

[meta]
name = "Synth Clavinet 3"
author = "Vulpus Labs"
category = "Keys"
comment = "Translated from DX7 factory ROM 'SYN-CLAV 3': algo 2, feedback 2."

[params]
algo = 2
feedback = 1.4

# op1
op1-num = 1
op1-level = 99
op1-vel-sens = 2
op1-eg-r1 = 80
op1-eg-r2 = 32
op1-eg-r3 = 18
op1-eg-r4 = 66
op1-eg-l1 = 99
op1-eg-l2 = 95
op1-eg-l3 = 90
op1-eg-l4 = 0
op1-ks-rate = 7
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 1
op2-level = 99
op2-vel-sens = 2
op2-eg-r1 = 80
op2-eg-r2 = 7
op2-eg-r3 = 21
op2-eg-r4 = 30
op2-eg-l1 = 99
op2-eg-l2 = 85
op2-eg-l3 = 80
op2-eg-l4 = 0
op2-ks-rate = 7
op2-ks-l-depth = 0
op2-ks-r-depth = 0

# op3
op3-num = 1
op3-detune = 2
op3-level = 99
op3-vel-sens = 2
op3-eg-r1 = 95
op3-eg-r2 = 17
op3-eg-r3 = 17
op3-eg-r4 = 66
op3-eg-l1 = 99
op3-eg-l2 = 95
op3-eg-l3 = 70
op3-eg-l4 = 0
op3-ks-rate = 7
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 1
op4-denom = 2
op4-detune = 3
op4-level = 96
op4-vel-sens = 7
op4-eg-r1 = 95
op4-eg-r2 = 16
op4-eg-r3 = 15
op4-eg-r4 = 30
op4-eg-l1 = 99
op4-eg-l2 = 85
op4-eg-l3 = 96
op4-eg-l4 = 0
op4-ks-rate = 7
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 12
op5-level = 80
op5-vel-sens = 1
op5-eg-r1 = 94
op5-eg-r2 = 17
op5-eg-r3 = 15
op5-eg-r4 = 40
op5-eg-l1 = 99
op5-eg-l2 = 87
op5-eg-l3 = 79
op5-eg-l4 = 0
op5-ks-rate = 7
op5-ks-break-pt = 31
op5-ks-l-depth = 0
op5-ks-r-depth = 50
op5-ks-r-curve = "neg-exp"

# op6
op6-num = 12
op6-detune = 2
op6-level = 70
op6-vel-sens = 1
op6-eg-r1 = 93
op6-eg-r2 = 16
op6-eg-r3 = 17
op6-eg-r4 = 30
op6-eg-l1 = 77
op6-eg-l2 = 51
op6-eg-l3 = 88
op6-eg-l4 = 0
op6-ks-rate = 7
op6-ks-l-depth = 0
op6-ks-r-depth = 0

lfo2-shape = "S&H"
lfo2-rate = 8.06
lfo2-delay = 1020.0
lfo2-fade = 0.0

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -17.98

[[matrix]]
slot = 0
source = "lfo2"
dest = "op2-level"
depth = 0.3

[[matrix]]
slot = 1
source = "lfo2"
dest = "op3-level"
depth = 0.1

[[matrix]]
slot = 2
source = "lfo2"
dest = "op5-level"
depth = 0.3

[[matrix]]
slot = 3
source = "lfo2"
dest = "op6-level"
depth = 0.3
