schema = 1

[meta]
name = "SYNBRASS 1"
author = "Vulpus Labs"
category = "Brass"
comment = "Translated from DX7 factory ROM 'SYNBRASS 1': algo 22, feedback 7."

[params]
algo = 22
feedback = 4.9

# op1
op1-num = 1
op1-detune = 5
op1-level = 99
op1-vel-sens = 0
op1-eg-r1 = 99
op1-eg-r2 = 76
op1-eg-r3 = 99
op1-eg-r4 = 71
op1-eg-l1 = 99
op1-eg-l2 = 88
op1-eg-l3 = 96
op1-eg-l4 = 0
op1-ks-rate = 0
op1-ks-break-pt = 60
op1-ks-l-depth = 0
op1-ks-r-depth = 14
op1-ks-r-curve = "pos-lin"

# op2
op2-num = 1
op2-denom = 2
op2-detune = 5
op2-level = 91
op2-vel-sens = 0
op2-eg-r1 = 25
op2-eg-r2 = 16
op2-eg-r3 = 18
op2-eg-r4 = 71
op2-eg-l1 = 92
op2-eg-l2 = 95
op2-eg-l3 = 93
op2-eg-l4 = 0
op2-ks-rate = 0
op2-ks-l-depth = 0
op2-ks-r-depth = 0

# op3
op3-num = 1
op3-denom = 2
op3-detune = -2
op3-level = 99
op3-vel-sens = 0
op3-eg-r1 = 99
op3-eg-r2 = 76
op3-eg-r3 = 82
op3-eg-r4 = 71
op3-eg-l1 = 99
op3-eg-l2 = 98
op3-eg-l3 = 98
op3-eg-l4 = 0
op3-ks-rate = 0
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 1
op4-denom = 2
op4-detune = -1
op4-level = 99
op4-vel-sens = 0
op4-eg-r1 = 99
op4-eg-r2 = 36
op4-eg-r3 = 41
op4-eg-r4 = 71
op4-eg-l1 = 99
op4-eg-l2 = 98
op4-eg-l3 = 98
op4-eg-l4 = 0
op4-ks-rate = 0
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 1
op5-denom = 2
op5-detune = 1
op5-level = 99
op5-vel-sens = 0
op5-eg-r1 = 99
op5-eg-r2 = 36
op5-eg-r3 = 41
op5-eg-r4 = 71
op5-eg-l1 = 99
op5-eg-l2 = 98
op5-eg-l3 = 98
op5-eg-l4 = 0
op5-ks-rate = 0
op5-ks-l-depth = 0
op5-ks-r-depth = 0

# op6
op6-num = 1
op6-denom = 2
op6-level = 83
op6-vel-sens = 2
op6-eg-r1 = 99
op6-eg-r2 = 32
op6-eg-r3 = 28
op6-eg-r4 = 68
op6-eg-l1 = 98
op6-eg-l2 = 98
op6-eg-l3 = 92
op6-eg-l4 = 0
op6-ks-rate = 4
op6-ks-l-depth = 0
op6-ks-r-depth = 0

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -15.04
