//! In-process integration smoke for `vxn4-clap`.
//!
//! Drives the plugin through the real CLAP lifecycle via clack-host — `init` →
//! `activate` → `start_processing` → `process` — and asserts the things that
//! can only be wrong end to end: that the entry and descriptor load, that a
//! note produces audio, that host automation reaches the engine, and that
//! state round-trips through the `state` extension.
//!
//! Loaded through the in-process `rlib`, so a panic surfaces with a real
//! backtrace and nothing goes through `dlopen`. If this passes, the entry,
//! factory, descriptor, ports, param table, event dispatch and process wiring
//! are correct together — which is what "loads in a host" actually means.

use clack_host::events::event_types::{NoteOnEvent, ParamValueEvent};
use clack_host::events::{Match, Pckn};
use clack_host::factory::plugin::PluginFactory;
use clack_host::prelude::*;
use clack_host::utils::Cookie;
use clack_plugin::clack_entry;
use clack_plugin::prelude::{EntryDescriptor, SinglePluginEntry};

use vxn4_clap::VxnPlugin;
use vxn4_clap::params::{self, Slot, TOTAL_PARAMS};

static VXN_ENTRY: EntryDescriptor = clack_entry!(SinglePluginEntry<VxnPlugin>);

const SAMPLE_RATE: f64 = 48_000.0;
const MAX_FRAMES: u32 = 256;
const PLUGIN_ID: &core::ffi::CStr = c"labs.vulpus.vxn4";

struct TestHostShared;
impl SharedHandler<'_> for TestHostShared {
    fn request_restart(&self) {}
    fn request_process(&self) {}
    fn request_callback(&self) {}
}

struct TestHost;
impl HostHandlers for TestHost {
    type Shared<'a> = TestHostShared;
    type MainThread<'a> = ();
    type AudioProcessor<'a> = ();
}

fn load_entry() -> PluginEntry {
    // SAFETY: VXN_ENTRY is generated by clack's own macro.
    unsafe { PluginEntry::load_from_raw(&VXN_ENTRY, c"/tmp/VXN4.clap") }.unwrap()
}

fn host_info() -> HostInfo {
    HostInfo::new("VXN4 Smoke", "Vulpus Labs", "https://vulpus.labs", "0.0.0").unwrap()
}

fn instantiate(entry: &PluginEntry) -> PluginInstance<TestHost> {
    PluginInstance::<TestHost>::new(|_| TestHostShared, |_| (), entry, PLUGIN_ID, &host_info())
        .expect("instantiation failed")
}

fn activate_started(
    instance: &mut PluginInstance<TestHost>,
) -> StartedPluginAudioProcessor<TestHost> {
    let cfg = PluginAudioConfiguration {
        sample_rate: SAMPLE_RATE,
        min_frames_count: 1,
        max_frames_count: MAX_FRAMES,
    };
    instance
        .activate(|_, _| (), cfg)
        .expect("activation failed")
        .start_processing()
        .expect("start_processing failed")
}

/// One `process()` call with the given input events, into a stereo f32 port.
fn process_one(
    processor: &mut StartedPluginAudioProcessor<TestHost>,
    in_events: &EventBuffer,
    out_l: &mut [f32],
    out_r: &mut [f32],
    steady_time: u64,
) {
    let mut out_events = EventBuffer::with_capacity(0);
    let inputs = InputAudioBuffers::empty();
    let mut output_ports = AudioPorts::with_capacity(2, 1);
    let chans: [&mut [f32]; 2] = [out_l, out_r];
    let mut outputs = output_ports.with_output_buffers([AudioPortBuffer {
        channels: AudioPortBufferType::f32_output_only(chans.into_iter()),
        latency: 0,
    }]);
    processor
        .process(
            &inputs,
            &mut outputs,
            &in_events.as_input(),
            &mut out_events.as_output(),
            Some(steady_time),
            None,
        )
        .expect("process failed");
}

fn note_on(buf: &mut EventBuffer, key: u16, velocity: f64, time: u32) {
    buf.push(&NoteOnEvent::new(
        time,
        Pckn::new(0u16, 0u16, key, Match::All),
        velocity,
    ));
}

fn param(buf: &mut EventBuffer, id: usize, value: f64, time: u32) {
    buf.push(&ParamValueEvent::new(
        time,
        ClapId::new(id as u32),
        Pckn::match_all(),
        value,
        Cookie::empty(),
    ));
}

/// Render `blocks` blocks and return the peak absolute sample.
fn peak_over(
    processor: &mut StartedPluginAudioProcessor<TestHost>,
    first: &EventBuffer,
    blocks: usize,
) -> f32 {
    let empty = EventBuffer::with_capacity(0);
    let mut peak = 0.0f32;
    let mut steady = 0u64;
    for b in 0..blocks {
        let mut l = vec![0.0f32; MAX_FRAMES as usize];
        let mut r = vec![0.0f32; MAX_FRAMES as usize];
        let evs = if b == 0 { first } else { &empty };
        process_one(processor, evs, &mut l, &mut r, steady);
        steady += MAX_FRAMES as u64;
        for &v in l.iter().chain(r.iter()) {
            assert!(v.is_finite(), "non-finite sample {v}");
            peak = peak.max(v.abs());
        }
    }
    peak
}

#[test]
fn the_entry_loads_and_describes_vxn4() {
    let entry = load_entry();
    let factory = entry.get_factory::<PluginFactory>().unwrap();
    assert_eq!(factory.plugin_count(), 1);
    let desc = factory.plugin_descriptor(0).unwrap();
    assert_eq!(desc.id().unwrap().to_str().unwrap(), "labs.vulpus.vxn4");
    assert_eq!(desc.name().unwrap().to_str().unwrap(), "VXN4");
}

#[test]
fn silence_in_silence_out() {
    let entry = load_entry();
    let mut instance = instantiate(&entry);
    let mut processor = activate_started(&mut instance);
    let empty = EventBuffer::with_capacity(0);
    assert_eq!(peak_over(&mut processor, &empty, 8), 0.0);
}

/// The whole point: a note in, audio out, through the real event path.
#[test]
fn a_note_produces_audio() {
    let entry = load_entry();
    let mut instance = instantiate(&entry);
    let mut processor = activate_started(&mut instance);

    let mut evs = EventBuffer::with_capacity(1);
    note_on(&mut evs, 60, 0.8, 0);
    let peak = peak_over(&mut processor, &evs, 16);
    assert!(peak > 0.01, "a note-on produced peak {peak}");
    assert!(peak <= 1.0, "output left full scale at {peak}");
}

/// Host automation has to reach the engine, and a macro has to change the
/// sound. Both patches here are `sine`, whose only route is macro 1 onto its
/// own feedback diagonal — so a difference between these two renders is the
/// matrix running end to end from a CLAP event.
#[test]
fn a_macro_automation_lane_changes_the_sound() {
    let render = |macro1: Option<f64>| {
        let entry = load_entry();
        let mut instance = instantiate(&entry);
        let mut processor = activate_started(&mut instance);

        let mut evs = EventBuffer::with_capacity(2);
        if let Some(v) = macro1 {
            param(&mut evs, params::N_FIXED, v, 0);
        }
        note_on(&mut evs, 69, 0.8, 0);

        let empty = EventBuffer::with_capacity(0);
        let mut all = Vec::new();
        let mut steady = 0u64;
        for b in 0..24 {
            let mut l = vec![0.0f32; MAX_FRAMES as usize];
            let mut r = vec![0.0f32; MAX_FRAMES as usize];
            process_one(
                &mut processor,
                if b == 0 { &evs } else { &empty },
                &mut l,
                &mut r,
                steady,
            );
            steady += MAX_FRAMES as u64;
            all.extend_from_slice(&l);
        }
        all
    };

    let plain = render(None);
    let modulated = render(Some(1.0));
    assert_ne!(plain, modulated, "macro 1 never reached the engine");
    assert!(modulated.iter().all(|s| s.is_finite()));
}

/// Selecting a patch through automation must change the instrument.
#[test]
fn the_patch_parameter_selects_a_patch() {
    let peak_of = |patch: f64| {
        let entry = load_entry();
        let mut instance = instantiate(&entry);
        let mut processor = activate_started(&mut instance);
        let mut evs = EventBuffer::with_capacity(2);
        param(&mut evs, 0, patch, 0);
        note_on(&mut evs, 60, 1.0, 0);
        peak_over(&mut processor, &evs, 24)
    };
    // Every patch has to sound, and none may leave full scale.
    for p in 0..vxn4_engine::N_PATCHES {
        let peak = peak_of(p as f64);
        assert!(peak > 0.005, "patch {p} was silent (peak {peak})");
        assert!(peak <= 1.0, "patch {p} reached {peak}");
    }
}

/// Events land at their own sample offset, not at the block boundary. A note
/// placed late in the block must leave the samples before it silent.
#[test]
fn an_event_lands_at_its_own_sample_offset() {
    let entry = load_entry();
    let mut instance = instantiate(&entry);
    let mut processor = activate_started(&mut instance);

    let at = MAX_FRAMES / 2;
    let mut evs = EventBuffer::with_capacity(1);
    note_on(&mut evs, 60, 1.0, at);

    let mut l = vec![0.0f32; MAX_FRAMES as usize];
    let mut r = vec![0.0f32; MAX_FRAMES as usize];
    process_one(&mut processor, &evs, &mut l, &mut r, 0);

    let before = l[..at as usize].iter().fold(0.0f32, |m, s| m.max(s.abs()));
    assert_eq!(before, 0.0, "audio appeared before the note-on offset");
}

/// Parameter values survive a deactivate/reactivate without being resent.
///
/// This is the path a project reload takes: the values live in the shared
/// cache, and `activate` seeds a fresh engine from it. If the seeding were
/// missing, the reactivated instance would silently revert to patch 0 with
/// every macro at zero — which sounds like a plugin that works, right up until
/// someone reopens a project.
///
/// Two patches with clearly different levels, compared across the boundary.
/// The blob format itself is pinned by the unit tests in `state.rs`; what needs
/// an in-process host is the seeding, which those cannot reach.
#[test]
fn parameters_survive_a_reactivate_without_being_resent() {
    let entry = load_entry();
    let mut instance = instantiate(&entry);

    let mut processor = activate_started(&mut instance);
    let mut evs = EventBuffer::with_capacity(4);
    param(&mut evs, 0, 5.0, 0); // patch: grind
    param(&mut evs, 2, 0.25, 0); // master gain, well down
    param(&mut evs, params::N_FIXED, 1.0, 0); // macro 1 wide open
    note_on(&mut evs, 60, 1.0, 0);
    let before = peak_over(&mut processor, &evs, 16);
    assert!(before > 0.0005, "the first instance was silent ({before})");

    instance.deactivate(processor.stop_processing());

    // Reactivate with no events at all: same patch, same trim, same macro.
    let mut processor = activate_started(&mut instance);
    let mut evs = EventBuffer::with_capacity(1);
    note_on(&mut evs, 60, 1.0, 0);
    let after = peak_over(&mut processor, &evs, 16);

    assert!(after > 0.0005, "the reactivated engine was silent");
    // The trim is the discriminating one: at 0.25 it is 12 dB below default,
    // so a lost cache would show up here as a much louder render.
    assert!(
        (after / before - 1.0).abs() < 0.25,
        "state was not carried across activate ({before} -> {after})"
    );
}

/// The param table the host enumerates is the one the code decodes.
#[test]
fn every_declared_param_decodes() {
    for id in 0..TOTAL_PARAMS {
        let slot = params::decode(id).unwrap_or_else(|| panic!("id {id}"));
        let (min, max, default, _) = params::range(slot);
        assert!(
            min <= default && default <= max,
            "{slot:?} default out of range"
        );
    }
    assert!(matches!(params::decode(0), Some(Slot::Patch)));
}
