#!/usr/bin/env python3
"""Recalibrate the pitch EG + vibrato depth of the DX7-derived factory presets.

One-off migration for the pitch-calibration fix. The bank was generated by
`dx7_to_vxn2.py` and then curated by hand (display names, gain-match), so a
straight regeneration would throw that work away. This rewrites *only* the
`peg-*` lines and the `lfo2 -> global-pitch` route depth, re-deriving both from
the ROM voice named in each preset's `comment` field.

Both quantities were mis-scaled:
  * levels ran ~2.6x deep — `(raw-50)*2` against a fixed 48 st depth, instead of
    the DX7 level table's 1/32-octave units;
  * the vibrato depth was fed in linearly to a matrix dest that cubes it, which
    left a 28-cent vibrato at 0.03 cents.

Idempotent: re-running over already-migrated presets is a no-op.
"""
import os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import dx7decode as dec
from dx7_to_vxn2 import BANKS, OUT, rom_dir, peg_block, vibrato_semitones

COMMENT_RE = re.compile(r"Translated from DX7 factory ROM '(.*?)'")
PEG_RE = re.compile(r"^peg-(?:r[1-4]|l[1-4]|depth) = .*$")


def load_rom_voices():
    """DX7 voice name -> decoded voice, keyed the way the preset `comment`
    records it (outer padding stripped, inner spacing kept). First bank wins,
    which is the dedup order `dx7_to_vxn2.py` used when it emitted the bank."""
    roms, out = rom_dir(), {}
    for b in BANKS:
        path = os.path.join(roms, b + ".syx")
        body = open(path, "rb").read()[6:6 + 4096]
        for vi in range(32):
            v = dec.unpack(body[vi * 128:(vi + 1) * 128])
            out.setdefault(v['name'].strip(), v)
    return out


def patch(text, voice):
    """Return (new_text, changed_peg, changed_vib)."""
    lines = text.split("\n")
    peg = [l.rstrip() for l in peg_block(voice['peg_r'], voice['peg_l']) if l]

    # Splice the peg block over the old one, keeping its position in the file.
    first = next((i for i, l in enumerate(lines) if PEG_RE.match(l)), None)
    changed_peg = False
    if first is not None:
        last = first
        while last + 1 < len(lines) and PEG_RE.match(lines[last + 1]):
            last += 1
        if lines[first:last + 1] != peg:
            lines[first:last + 1] = peg
            changed_peg = True
    elif peg:
        raise SystemExit(f"ROM voice {voice['name']!r} has a pitch EG but the "
                         f"preset has no peg- lines to replace")

    # Vibrato: rewrite the depth of the lfo2 -> global-pitch route in place.
    st = vibrato_semitones(voice['lfo_pmd'], voice['lfo_pms'])
    depth = round(min(1.0, (st / 24.0) ** (1.0 / 3.0)), 4)
    changed_vib = False
    for i, l in enumerate(lines):
        if l != 'dest = "global-pitch"':
            continue
        if lines[i - 1] != 'source = "lfo2"':
            continue
        j = i + 1
        while j < len(lines) and not lines[j].startswith("depth = "):
            j += 1
        if j < len(lines) and lines[j] != f"depth = {depth}":
            lines[j] = f"depth = {depth}"
            changed_vib = True
    return "\n".join(lines), changed_peg, changed_vib


def main():
    voices = load_rom_voices()
    n_peg = n_vib = n_files = 0
    for root, _, files in os.walk(OUT):
        for f in sorted(files):
            if not f.endswith(".toml"):
                continue
            path = os.path.join(root, f)
            text = open(path).read()
            m = COMMENT_RE.search(text)
            if not m:
                continue                      # hand-authored preset
            name = m.group(1)
            if name not in voices:
                print(f"  ?? no ROM voice {name!r} for {os.path.relpath(path, OUT)}")
                continue
            new, cp, cv = patch(text, voices[name])
            if new != text:
                open(path, "w").write(new)
                n_files += 1
                n_peg += cp
                n_vib += cv
    print(f"rewrote {n_files} presets: {n_peg} pitch EG, {n_vib} vibrato depth")


if __name__ == "__main__":
    main()
