schema = 1

[meta]
name = "E.ORGAN 4"
author = "Vulpus Labs"
category = "Organ"
comment = "Translated from DX7 factory ROM 'E.ORGAN 4': algo 5, feedback 7."

[params]
algo = 5
feedback = 4.9

# op1
op1-num = 1
op1-denom = 2
op1-detune = -1
op1-level = 95
op1-vel-sens = 0
op1-eg-r1 = 97
op1-eg-r2 = 97
op1-eg-r3 = 99
op1-eg-r4 = 82
op1-eg-l1 = 99
op1-eg-l2 = 99
op1-eg-l3 = 99
op1-eg-l4 = 0
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 1
op2-denom = 2
op2-detune = 1
op2-level = 82
op2-vel-sens = 7
op2-eg-r1 = 97
op2-eg-r2 = 97
op2-eg-r3 = 99
op2-eg-r4 = 82
op2-eg-l1 = 99
op2-eg-l2 = 99
op2-eg-l3 = 97
op2-eg-l4 = 0
op2-ks-l-depth = 0
op2-ks-r-depth = 0

# op3
op3-num = 1
op3-detune = 5
op3-level = 99
op3-vel-sens = 0
op3-eg-r1 = 97
op3-eg-r2 = 97
op3-eg-r3 = 99
op3-eg-r4 = 82
op3-eg-l1 = 99
op3-eg-l2 = 99
op3-eg-l3 = 97
op3-eg-l4 = 0
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 1
op4-denom = 2
op4-detune = -1
op4-level = 99
op4-vel-sens = 7
op4-eg-r1 = 79
op4-eg-r2 = 98
op4-eg-r3 = 99
op4-eg-r4 = 82
op4-eg-l1 = 99
op4-eg-l2 = 89
op4-eg-l3 = 80
op4-eg-l4 = 0
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 5
op5-level = 99
op5-vel-sens = 7
op5-eg-r1 = 97
op5-eg-r2 = 99
op5-eg-r3 = 50
op5-eg-r4 = 82
op5-eg-l1 = 99
op5-eg-l2 = 90
op5-eg-l3 = 84
op5-eg-l4 = 0
op5-ks-l-depth = 0
op5-ks-r-depth = 0

# op6
op6-num = 4
op6-detune = 5
op6-level = 99
op6-vel-sens = 0
op6-eg-r1 = 91
op6-eg-r2 = 79
op6-eg-r3 = 99
op6-eg-r4 = 82
op6-eg-l1 = 86
op6-eg-l2 = 50
op6-eg-l3 = 0
op6-eg-l4 = 0
op6-ks-l-depth = 0
op6-ks-r-depth = 0

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -11.65
