schema = 1

[meta]
name = "PIPES 3"
author = "Vulpus Labs"
category = "Organ"
comment = "Translated from DX7 factory ROM 'PIPES   3': algo 25, feedback 3."

[params]
algo = 25
feedback = 2.1

# op1
op1-num = 1
op1-fine = -50
op1-level = 99
op1-vel-sens = 0
op1-eg-r1 = 77
op1-eg-r2 = 80
op1-eg-r3 = 74
op1-eg-r4 = 48
op1-eg-l1 = 99
op1-eg-l2 = 97
op1-eg-l3 = 99
op1-eg-l4 = 0
op1-ks-break-pt = 56
op1-ks-l-depth = 13
op1-ks-r-depth = 10
op1-ks-l-curve = "pos-lin"
op1-ks-r-curve = "neg-lin"

# op2
op2-num = 4
op2-fine = 4
op2-level = 99
op2-vel-sens = 0
op2-eg-r1 = 99
op2-eg-r2 = 99
op2-eg-r3 = 57
op2-eg-r4 = 64
op2-eg-l1 = 57
op2-eg-l2 = 52
op2-eg-l3 = 99
op2-eg-l4 = 0
op2-ks-rate = 0
op2-ks-break-pt = 21
op2-ks-l-depth = 0
op2-ks-r-depth = 30
op2-ks-r-curve = "neg-lin"

# op3
op3-num = 1
op3-fine = 1
op3-level = 87
op3-vel-sens = 0
op3-eg-r1 = 76
op3-eg-r2 = 80
op3-eg-r3 = 22
op3-eg-r4 = 63
op3-eg-l1 = 99
op3-eg-l2 = 99
op3-eg-l3 = 99
op3-eg-l4 = 0
op3-ks-rate = 4
op3-ks-break-pt = 56
op3-ks-l-depth = 13
op3-ks-r-depth = 15
op3-ks-r-curve = "neg-lin"

# op4
op4-num = 2
op4-fine = 2
op4-detune = -1
op4-level = 98
op4-vel-sens = 0
op4-eg-r1 = 73
op4-eg-r2 = 80
op4-eg-r3 = 22
op4-eg-r4 = 50
op4-eg-l1 = 79
op4-eg-l2 = 99
op4-eg-l3 = 99
op4-eg-l4 = 0
op4-ks-rate = 0
op4-ks-break-pt = 21
op4-ks-l-depth = 0
op4-ks-r-depth = 20
op4-ks-r-curve = "neg-lin"

# op5
op5-num = 8
op5-fine = 8
op5-level = 80
op5-vel-sens = 0
op5-eg-r1 = 88
op5-eg-r2 = 68
op5-eg-r3 = 22
op5-eg-r4 = 75
op5-eg-l1 = 60
op5-eg-l2 = 99
op5-eg-l3 = 99
op5-eg-l4 = 0
op5-ks-rate = 0
op5-ks-break-pt = 21
op5-ks-l-depth = 0
op5-ks-r-depth = 50
op5-ks-r-curve = "neg-exp"

# op6
op6-num = 4
op6-fine = 4
op6-level = 58
op6-vel-sens = 0
op6-eg-r1 = 89
op6-eg-r2 = 80
op6-eg-r3 = 22
op6-eg-r4 = 65
op6-eg-l1 = 99
op6-eg-l2 = 99
op6-eg-l3 = 99
op6-eg-l4 = 0
op6-ks-rate = 0
op6-ks-break-pt = 21
op6-ks-l-depth = 0
op6-ks-r-depth = 60
op6-ks-r-curve = "neg-exp"

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -16.8
