schema = 1

[meta]
name = "PIPES 1"
author = "Vulpus Labs"
category = "Organ"
comment = "Translated from DX7 factory ROM 'PIPES   1': algo 19, feedback 7. DX7 transpose -12 st baked into ratios."

[params]
algo = 19
feedback = 4.9

# op1
op1-num = 1
op1-fine = -75
op1-level = 99
op1-vel-sens = 0
op1-eg-r1 = 45
op1-eg-r2 = 25
op1-eg-r3 = 25
op1-eg-r4 = 36
op1-eg-l1 = 99
op1-eg-l2 = 99
op1-eg-l3 = 98
op1-eg-l4 = 0
op1-ks-rate = 5
op1-ks-break-pt = 62
op1-ks-l-depth = 0
op1-ks-r-depth = 50
op1-ks-r-curve = "neg-lin"

# op2
op2-num = 1
op2-fine = -75
op2-level = 90
op2-vel-sens = 0
op2-eg-r1 = 99
op2-eg-r2 = 97
op2-eg-r3 = 62
op2-eg-r4 = 47
op2-eg-l1 = 99
op2-eg-l2 = 99
op2-eg-l3 = 90
op2-eg-l4 = 0
op2-ks-rate = 4
op2-ks-l-depth = 0
op2-ks-r-depth = 0

# op3
op3-num = 1
op3-fine = -50
op3-level = 75
op3-vel-sens = 0
op3-eg-r1 = 99
op3-eg-r2 = 97
op3-eg-r3 = 62
op3-eg-r4 = 47
op3-eg-l1 = 99
op3-eg-l2 = 99
op3-eg-l3 = 90
op3-eg-l4 = 0
op3-ks-rate = 5
op3-ks-break-pt = 67
op3-ks-l-depth = 17
op3-ks-r-depth = 40
op3-ks-l-curve = "pos-lin"
op3-ks-r-curve = "neg-lin"

# op4
op4-num = 2
op4-level = 88
op4-vel-sens = 0
op4-eg-r1 = 61
op4-eg-r2 = 25
op4-eg-r3 = 25
op4-eg-r4 = 50
op4-eg-l1 = 99
op4-eg-l2 = 99
op4-eg-l3 = 97
op4-eg-l4 = 0
op4-ks-rate = 3
op4-ks-break-pt = 81
op4-ks-l-depth = 10
op4-ks-r-depth = 10
op4-ks-r-curve = "neg-lin"

# op5
op5-num = 1
op5-level = 97
op5-vel-sens = 0
op5-eg-r1 = 61
op5-eg-r2 = 25
op5-eg-r3 = 25
op5-eg-r4 = 61
op5-eg-l1 = 99
op5-eg-l2 = 99
op5-eg-l3 = 93
op5-eg-l4 = 0
op5-ks-rate = 3
op5-ks-l-depth = 0
op5-ks-r-depth = 0

# op6
op6-num = 5
op6-level = 76
op6-vel-sens = 2
op6-eg-r1 = 72
op6-eg-r2 = 25
op6-eg-r3 = 25
op6-eg-r4 = 70
op6-eg-l1 = 99
op6-eg-l2 = 99
op6-eg-l3 = 99
op6-eg-l4 = 0
op6-ks-rate = 3
op6-ks-break-pt = 67
op6-ks-l-depth = 10
op6-ks-r-depth = 1
op6-ks-r-curve = "pos-lin"

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -12.4
