schema = 1

[meta]
name = "TAKE OFF"
author = "Vulpus Labs"
category = "FX"
comment = "Translated from DX7 factory ROM 'TAKE OFF': algo 10, feedback 0. DX7 transpose -24 st baked into ratios."

[params]
algo = 10

# op1
op1-num = 1
op1-detune = 1
op1-level = 99
op1-vel-sens = 0
op1-eg-r1 = 9
op1-eg-r2 = 14
op1-eg-r3 = 17
op1-eg-r4 = 34
op1-eg-l1 = 61
op1-eg-l2 = 96
op1-eg-l3 = 0
op1-eg-l4 = 0
op1-ks-rate = 0
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 1
op2-denom = 4
op2-level = 96
op2-vel-sens = 0
op2-eg-r1 = 82
op2-eg-r2 = 80
op2-eg-r3 = 19
op2-eg-r4 = 14
op2-eg-l1 = 80
op2-eg-l2 = 95
op2-eg-l3 = 0
op2-eg-l4 = 0
op2-ks-rate = 0
op2-ks-l-depth = 0
op2-ks-r-depth = 0

# op3
op3-num = 3
op3-denom = 2
op3-detune = 1
op3-level = 99
op3-vel-sens = 0
op3-eg-r1 = 76
op3-eg-r2 = 35
op3-eg-r3 = 99
op3-eg-r4 = 11
op3-eg-l1 = 67
op3-eg-l2 = 38
op3-eg-l3 = 73
op3-eg-l4 = 0
op3-ks-rate = 0
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 1
op4-denom = 8
op4-level = 99
op4-vel-sens = 0
op4-eg-r1 = 13
op4-eg-r2 = 14
op4-eg-r3 = 20
op4-eg-r4 = 30
op4-eg-l1 = 99
op4-eg-l2 = 95
op4-eg-l3 = 99
op4-eg-l4 = 0
op4-ks-rate = 0
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 1
op5-denom = 2
op5-detune = 1
op5-level = 96
op5-vel-sens = 0
op5-eg-r1 = 88
op5-eg-r2 = 24
op5-eg-r3 = 23
op5-eg-r4 = 37
op5-eg-l1 = 99
op5-eg-l2 = 90
op5-eg-l3 = 0
op5-eg-l4 = 0
op5-ks-rate = 0
op5-ks-l-depth = 0
op5-ks-r-depth = 0

# op6
op6-num = 1
op6-denom = 8
op6-level = 99
op6-vel-sens = 0
op6-eg-r1 = 89
op6-eg-r2 = 22
op6-eg-r3 = 20
op6-eg-r4 = 41
op6-eg-l1 = 99
op6-eg-l2 = 92
op6-eg-l3 = 0
op6-eg-l4 = 0
op6-ks-rate = 0
op6-ks-l-depth = 0
op6-ks-r-depth = 0

peg-r1 = 32
peg-r2 = 30
peg-r3 = 94
peg-r4 = 16
peg-l1 = 0
peg-l2 = -86
peg-l3 = 62
peg-l4 = 98

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -10.2
