//! In-process integration smoke for vxn2-clap.
//!
//! Drives the plugin through the real CLAP lifecycle via clack-host
//! (`init` → `activate(44.1k / 256)` → `start_processing` → `process`) and
//! exercises notes, automation, transport tempo, raw MIDI bend / mod-wheel,
//! and state save / restore. Closes E002: if every test here passes, the
//! kernel + CLAP shell + default patch + state extension are wired up
//! correctly end-to-end.
//!
//! Loads via the in-process `rlib` target so panics surface with real
//! backtraces; nothing here goes through `dlopen`.

use clack_extensions::latency::PluginLatency;
use clack_extensions::params::PluginParams;
use clack_extensions::state::PluginState;
use clack_host::events::event_types::{
    MidiEvent, NoteOffEvent, NoteOnEvent, ParamValueEvent, TransportEvent, TransportFlags,
};
use clack_host::events::{EventFlags, EventHeader, Pckn};
use clack_host::factory::plugin::PluginFactory;
use clack_host::prelude::*;
use clack_host::utils::{BeatTime, ClapId, Cookie, SecondsTime};
use clack_plugin::clack_entry;
use clack_plugin::prelude::{EntryDescriptor, SinglePluginEntry};
use vxn2_clap::VxnPlugin;
use vxn2_engine::params::id_of;
use vxn2_engine::{ParamKind, TOTAL_PARAMS, desc_for_clap_id};

static VXN_ENTRY: EntryDescriptor = clack_entry!(SinglePluginEntry<VxnPlugin>);

const SAMPLE_RATE: f64 = 44_100.0;
const MAX_FRAMES: u32 = 256;
const PLUGIN_ID: &core::ffi::CStr = c"labs.vulpus.vxn2";

// ── Host stub ───────────────────────────────────────────────────────────────

struct TestHostShared;
impl SharedHandler<'_> for TestHostShared {
    fn request_restart(&self) {}
    fn request_process(&self) {}
    fn request_callback(&self) {}
}

struct TestHost;
impl HostHandlers for TestHost {
    type Shared<'a> = TestHostShared;
    type MainThread<'a> = ();
    type AudioProcessor<'a> = ();
}

fn load_entry() -> PluginEntry {
    // SAFETY: VXN_ENTRY is generated by clack's own macro.
    unsafe { PluginEntry::load_from_raw(&VXN_ENTRY, c"/tmp/VXN2.clap") }.unwrap()
}

fn host_info() -> HostInfo {
    HostInfo::new("VXN2 Smoke", "Vulpus Labs", "https://vulpus.labs", "0.0.0").unwrap()
}

fn instantiate(entry: &PluginEntry) -> PluginInstance<TestHost> {
    PluginInstance::<TestHost>::new(
        |_| TestHostShared,
        |_| (),
        entry,
        PLUGIN_ID,
        &host_info(),
    )
    .expect("instantiation failed")
}

fn activate_started(
    instance: &mut PluginInstance<TestHost>,
    max_frames: u32,
) -> StartedPluginAudioProcessor<TestHost> {
    let cfg = PluginAudioConfiguration {
        sample_rate: SAMPLE_RATE,
        min_frames_count: 1,
        max_frames_count: max_frames,
    };
    instance
        .activate(|_, _| (), cfg)
        .expect("activation failed")
        .start_processing()
        .expect("start_processing failed")
}

/// Drive one `process()` call. Output port is stereo f32; the synth has no
/// audio inputs so we hand it an empty `InputAudioBuffers`.
fn process_one(
    processor: &mut StartedPluginAudioProcessor<TestHost>,
    in_events: &EventBuffer,
    out_events: &mut EventBuffer,
    transport: Option<&TransportEvent>,
    out_l: &mut [f32],
    out_r: &mut [f32],
    steady_time: u64,
) {
    assert_eq!(out_l.len(), out_r.len(), "channel length mismatch");
    let inputs = InputAudioBuffers::empty();
    let mut output_ports = AudioPorts::with_capacity(2, 1);
    let chans: [&mut [f32]; 2] = [out_l, out_r];
    let mut outputs = output_ports.with_output_buffers([AudioPortBuffer {
        channels: AudioPortBufferType::f32_output_only(chans.into_iter()),
        latency: 0,
    }]);
    let _ = processor
        .process(
            &inputs,
            &mut outputs,
            &in_events.as_input(),
            &mut out_events.as_output(),
            Some(steady_time),
            transport,
        )
        .expect("process failed");
}

/// Render `frames` samples worth of audio in `MAX_FRAMES`-size chunks,
/// appending the stereo result to `l_out` / `r_out`.
fn render_seconds(
    processor: &mut StartedPluginAudioProcessor<TestHost>,
    frames: usize,
    steady_time: &mut u64,
    l_out: &mut Vec<f32>,
    r_out: &mut Vec<f32>,
) {
    let in_events = EventBuffer::with_capacity(0);
    let mut out_events = EventBuffer::with_capacity(0);
    let mut remaining = frames;
    while remaining > 0 {
        let n = remaining.min(MAX_FRAMES as usize);
        let mut l = vec![0.0_f32; n];
        let mut r = vec![0.0_f32; n];
        process_one(
            processor,
            &in_events,
            &mut out_events,
            None,
            &mut l,
            &mut r,
            *steady_time,
        );
        *steady_time += n as u64;
        l_out.extend_from_slice(&l);
        r_out.extend_from_slice(&r);
        remaining -= n;
    }
}

fn rms_dbfs(samples: &[f32]) -> f32 {
    if samples.is_empty() {
        return f32::NEG_INFINITY;
    }
    let sum_sq: f64 = samples.iter().map(|&x| (x as f64) * (x as f64)).sum();
    let rms = (sum_sq / samples.len() as f64).sqrt() as f32;
    if rms <= 0.0 {
        f32::NEG_INFINITY
    } else {
        20.0 * rms.log10()
    }
}

fn note_on(time: u32, key: u16, velocity: f64) -> NoteOnEvent {
    NoteOnEvent::new(time, Pckn::new(0_u16, 0_u16, key, 0_u32), velocity)
}

fn note_off(time: u32, key: u16) -> NoteOffEvent {
    NoteOffEvent::new(time, Pckn::new(0_u16, 0_u16, key, 0_u32), 0.0)
}

fn param_event(time: u32, id: usize, value: f64) -> ParamValueEvent {
    ParamValueEvent::new(
        time,
        ClapId::new(id as u32),
        Pckn::match_all(),
        value,
        Cookie::empty(),
    )
}

/// Hand-rolled tempo transport event. clack-common doesn't expose a builder
/// for `TransportEvent`, so we fill the struct directly with `HAS_TEMPO` set.
fn tempo_transport(bpm: f64) -> TransportEvent {
    TransportEvent {
        header: EventHeader::new_core(0, EventFlags::empty()),
        flags: TransportFlags::HAS_TEMPO,
        song_pos_beats: BeatTime::from_int(0),
        song_pos_seconds: SecondsTime::from_int(0),
        tempo: bpm,
        tempo_inc: 0.0,
        loop_start_beats: BeatTime::from_int(0),
        loop_end_beats: BeatTime::from_int(0),
        loop_start_seconds: SecondsTime::from_int(0),
        loop_end_seconds: SecondsTime::from_int(0),
        bar_start: BeatTime::from_int(0),
        bar_number: 0,
        time_signature_numerator: 4,
        time_signature_denominator: 4,
    }
}

// ── 1. Entry / factory ──────────────────────────────────────────────────────

#[test]
fn entry_loads_and_describes_vxn2() {
    let entry = load_entry();
    let factory = entry.get_factory::<PluginFactory>().unwrap();
    assert_eq!(factory.plugin_count(), 1);
    let desc = factory.plugin_descriptor(0).unwrap();
    assert_eq!(desc.id().unwrap().to_str().unwrap(), "labs.vulpus.vxn2");
    assert_eq!(desc.name().unwrap().to_str().unwrap(), "VXN2");
}

// ── 2. Default-patch render ─────────────────────────────────────────────────

/// One-note default-patch render. Holds C4 for 1 s, releases, lets the tail
/// decay over 4 s. Checks: nothing NaN-tails, the attack RMS sits inside the
/// listening-test envelope, the post-release tail dies below the noise floor.
///
/// Bounds depend on the patch tuning in ticket 0018 — if 0018 shifts the
/// patch's loudness materially, update these here.
#[test]
fn default_patch_render_one_note() {
    let entry = load_entry();
    let mut instance = instantiate(&entry);
    let mut processor = activate_started(&mut instance, MAX_FRAMES);
    let mut steady = 0u64;

    let sr = SAMPLE_RATE as usize;
    let mut l = Vec::with_capacity(sr * 5);
    let mut r = Vec::with_capacity(sr * 5);

    // Sample 0: NoteOn(60).
    let mut on_buf = EventBuffer::with_capacity(1);
    on_buf.push(&note_on(0, 60, 0.8));
    let mut out_events = EventBuffer::with_capacity(0);
    let mut first_l = vec![0.0_f32; MAX_FRAMES as usize];
    let mut first_r = vec![0.0_f32; MAX_FRAMES as usize];
    process_one(
        &mut processor,
        &on_buf,
        &mut out_events,
        None,
        &mut first_l,
        &mut first_r,
        steady,
    );
    steady += MAX_FRAMES as u64;
    l.extend_from_slice(&first_l);
    r.extend_from_slice(&first_r);

    // Render the rest of the held-note second.
    render_seconds(&mut processor, sr - MAX_FRAMES as usize, &mut steady, &mut l, &mut r);

    // Sample 0 of the 1-second mark: NoteOff(60).
    let mut off_buf = EventBuffer::with_capacity(1);
    off_buf.push(&note_off(0, 60));
    let mut release_l = vec![0.0_f32; MAX_FRAMES as usize];
    let mut release_r = vec![0.0_f32; MAX_FRAMES as usize];
    process_one(
        &mut processor,
        &off_buf,
        &mut out_events,
        None,
        &mut release_l,
        &mut release_r,
        steady,
    );
    steady += MAX_FRAMES as u64;
    l.extend_from_slice(&release_l);
    r.extend_from_slice(&release_r);

    // Render 4 s of release tail.
    render_seconds(&mut processor, sr * 4 - MAX_FRAMES as usize, &mut steady, &mut l, &mut r);

    assert_eq!(l.len(), sr * 5);
    assert_eq!(r.len(), sr * 5);

    for (i, (&a, &b)) in l.iter().zip(r.iter()).enumerate() {
        assert!(a.is_finite(), "non-finite L at sample {i}: {a}");
        assert!(b.is_finite(), "non-finite R at sample {i}: {b}");
    }

    let attack_start = (sr as f32 * 0.1) as usize;
    let attack_end = (sr as f32 * 0.9) as usize;
    let attack_l = &l[attack_start..attack_end];
    let attack_r = &r[attack_start..attack_end];
    let attack_rms = 0.5 * (rms_dbfs(attack_l) + rms_dbfs(attack_r));
    assert!(
        (-24.0..=-9.0).contains(&attack_rms),
        "attack RMS out of band: {attack_rms} dBFS (want [-24, -9])"
    );

    let tail_start = (sr as f32 * 4.5) as usize;
    let tail_end = (sr as f32 * 4.99) as usize;
    let tail_rms =
        0.5 * (rms_dbfs(&l[tail_start..tail_end]) + rms_dbfs(&r[tail_start..tail_end]));
    assert!(
        tail_rms <= -60.0,
        "tail RMS too loud: {tail_rms} dBFS (want ≤ -60)"
    );
}

// ── 3. Parameter sweep ──────────────────────────────────────────────────────

/// Every CLAP id at `min` / midpoint / `max`, 128 samples per setting, with
/// C4 held throughout. Cheap "extremes don't crash / NaN" guard.
///
/// Won't catch slow audio bugs (a filter that quietly NaN-tails over seconds
/// of post-sweep render escapes), but does catch denormal explosions, panics
/// in stepped-param boundaries, and the obvious crash classes. Mirrors VXN1.
#[test]
fn parameter_sweep_min_mid_max_stays_finite() {
    let entry = load_entry();
    let mut instance = instantiate(&entry);
    let mut processor = activate_started(&mut instance, MAX_FRAMES);
    let mut steady = 0u64;

    const CHUNK: usize = 128;

    let mut on_buf = EventBuffer::with_capacity(1);
    on_buf.push(&note_on(0, 64, 0.7));
    let mut out_events = EventBuffer::with_capacity(0);
    {
        let mut l = vec![0.0_f32; CHUNK];
        let mut r = vec![0.0_f32; CHUNK];
        process_one(
            &mut processor,
            &on_buf,
            &mut out_events,
            None,
            &mut l,
            &mut r,
            steady,
        );
        steady += CHUNK as u64;
    }

    for id in 0..TOTAL_PARAMS {
        let desc = desc_for_clap_id(id).expect("descriptor for id");
        let mid = ((desc.min as f64) + (desc.max as f64)) * 0.5;
        for &v in &[desc.min as f64, mid, desc.max as f64] {
            let mut buf = EventBuffer::with_capacity(1);
            buf.push(&param_event(0, id, v));
            let mut l = vec![0.0_f32; CHUNK];
            let mut r = vec![0.0_f32; CHUNK];
            process_one(
                &mut processor,
                &buf,
                &mut out_events,
                None,
                &mut l,
                &mut r,
                steady,
            );
            steady += CHUNK as u64;
            for (i, (&a, &b)) in l.iter().zip(r.iter()).enumerate() {
                assert!(
                    a.is_finite() && b.is_finite(),
                    "non-finite output for id={id} value={v} at sample {i}: \
                     L={a} R={b} (param {})",
                    desc.id
                );
            }
        }
    }
}

// ── 4. State save / restore round-trip ──────────────────────────────────────

/// Spread non-default values across the table via host param events, render
/// a few blocks (so `publish()` propagates the audio-mirror back to the
/// shared store), `save` into a `Vec<u8>`, instantiate a fresh plugin,
/// `load` the blob, and assert every CLAP id's `get_value` matches.
#[test]
fn state_round_trip_preserves_every_param() {
    let entry = load_entry();
    let mut instance = instantiate(&entry);
    let mut processor = activate_started(&mut instance, MAX_FRAMES);
    let mut steady = 0u64;

    // Mix of float / int / enum / bool ids spanning per-op / master /
    // matrix / FX. Each value sits inside the descriptor's range.
    let edits: &[(&str, f64)] = &[
        ("master-volume", -3.0),
        ("master-tune", 5.0),
        ("op1-num", 3.0),
        ("op6-level", 88.0),
        ("op4-pan", -0.7),
        ("mtx1-depth", 0.4),
        ("mtx8-depth", -0.7),
        ("reverb-decay", 4.5),
        ("delay-time", 250.0),
        ("assign-mode", 1.0),
    ];
    let mut buf = EventBuffer::with_capacity(edits.len());
    for &(name, v) in edits {
        let id = id_of(name).unwrap_or_else(|| panic!("unknown id {name}"));
        buf.push(&param_event(0, id, v));
    }
    let mut out_events = EventBuffer::with_capacity(0);
    let mut l = vec![0.0_f32; MAX_FRAMES as usize];
    let mut r = vec![0.0_f32; MAX_FRAMES as usize];
    process_one(
        &mut processor,
        &buf,
        &mut out_events,
        None,
        &mut l,
        &mut r,
        steady,
    );
    steady += MAX_FRAMES as u64;

    // A few more blocks so any audio-thread `publish()` settles fully.
    let empty = EventBuffer::with_capacity(0);
    for _ in 0..4 {
        process_one(
            &mut processor,
            &empty,
            &mut out_events,
            None,
            &mut l,
            &mut r,
            steady,
        );
        steady += MAX_FRAMES as u64;
    }

    // Snapshot post-publish values via the host params extension.
    let mut handle = instance.plugin_handle();
    let params_ext = handle
        .get_extension::<PluginParams>()
        .expect("params extension");
    let state_ext = handle
        .get_extension::<PluginState>()
        .expect("state extension");

    let expected: Vec<f64> = (0..TOTAL_PARAMS)
        .map(|i| {
            params_ext
                .get_value(&mut handle, ClapId::new(i as u32))
                .expect("get_value")
        })
        .collect();

    let mut blob: Vec<u8> = Vec::new();
    state_ext
        .save(&mut handle, &mut blob)
        .expect("state save failed");
    assert!(!blob.is_empty(), "save produced empty blob");

    // Fresh instance, identical entry. Load into it and compare.
    let mut fresh = instantiate(&entry);
    let mut fresh_handle = fresh.plugin_handle();
    let fresh_state = fresh_handle
        .get_extension::<PluginState>()
        .expect("state extension on fresh");
    fresh_state
        .load(&mut fresh_handle, &mut blob.as_slice())
        .expect("state load failed");
    let fresh_params = fresh_handle
        .get_extension::<PluginParams>()
        .expect("params extension on fresh");

    for i in 0..TOTAL_PARAMS {
        let got = fresh_params
            .get_value(&mut fresh_handle, ClapId::new(i as u32))
            .expect("get_value on fresh");
        let want = expected[i];
        let eps = match desc_for_clap_id(i).unwrap().kind {
            ParamKind::Float { .. } => 1e-4,
            _ => 1e-9,
        };
        assert!(
            (got - want).abs() <= eps,
            "param {i} round-trip mismatch: want {want} got {got}"
        );
    }
}

// ── 5. Transport tempo edits ────────────────────────────────────────────────

/// Render across a 90 → 180 BPM transport edit. The engine reads tempo on
/// every block, so all we're guarding here is "no panic / no NaN at the
/// boundary"; audible sync correctness is a manual listening test.
#[test]
fn tempo_edit_does_not_break_render() {
    let entry = load_entry();
    let mut instance = instantiate(&entry);
    let mut processor = activate_started(&mut instance, MAX_FRAMES);
    let mut steady = 0u64;

    let mut on_buf = EventBuffer::with_capacity(1);
    on_buf.push(&note_on(0, 60, 0.8));
    let mut out_events = EventBuffer::with_capacity(0);
    let mut l = vec![0.0_f32; MAX_FRAMES as usize];
    let mut r = vec![0.0_f32; MAX_FRAMES as usize];
    let empty = EventBuffer::with_capacity(0);

    let t90 = tempo_transport(90.0);
    process_one(
        &mut processor,
        &on_buf,
        &mut out_events,
        Some(&t90),
        &mut l,
        &mut r,
        steady,
    );
    steady += MAX_FRAMES as u64;
    for &v in l.iter().chain(r.iter()) {
        assert!(v.is_finite(), "non-finite at 90 BPM: {v}");
    }

    let t180 = tempo_transport(180.0);
    process_one(
        &mut processor,
        &empty,
        &mut out_events,
        Some(&t180),
        &mut l,
        &mut r,
        steady,
    );
    for &v in l.iter().chain(r.iter()) {
        assert!(v.is_finite(), "non-finite at 180 BPM: {v}");
    }
}

// ── 6. Pitch bend / mod wheel via raw MIDI ──────────────────────────────────

/// Send pitch bend at its 14-bit extremes (full ±2 st with default range)
/// plus CC1 at 0 → 127 while a note holds. Just guards against panics + NaN
/// across the bend / wheel input path.
#[test]
fn pitch_bend_and_mod_wheel_stay_finite() {
    let entry = load_entry();
    let mut instance = instantiate(&entry);
    let mut processor = activate_started(&mut instance, MAX_FRAMES);
    let mut steady = 0u64;

    let mut on_buf = EventBuffer::with_capacity(1);
    on_buf.push(&note_on(0, 60, 0.9));
    let mut out_events = EventBuffer::with_capacity(0);
    let mut l = vec![0.0_f32; MAX_FRAMES as usize];
    let mut r = vec![0.0_f32; MAX_FRAMES as usize];
    process_one(
        &mut processor,
        &on_buf,
        &mut out_events,
        None,
        &mut l,
        &mut r,
        steady,
    );
    steady += MAX_FRAMES as u64;

    let bend_max: u16 = 0x3FFF;
    let bend_min: u16 = 0x0000;
    let bend_split = |raw: u16| ((raw & 0x7F) as u8, ((raw >> 7) & 0x7F) as u8);
    let (max_lsb, max_msb) = bend_split(bend_max);
    let (min_lsb, min_msb) = bend_split(bend_min);

    let mut midi_buf = EventBuffer::with_capacity(4);
    midi_buf.push(&MidiEvent::new(0, 0, [0xE0, max_lsb, max_msb]));
    midi_buf.push(&MidiEvent::new(64, 0, [0xE0, min_lsb, min_msb]));
    midi_buf.push(&MidiEvent::new(128, 0, [0xB0, 1, 0]));
    midi_buf.push(&MidiEvent::new(192, 0, [0xB0, 1, 127]));

    process_one(
        &mut processor,
        &midi_buf,
        &mut out_events,
        None,
        &mut l,
        &mut r,
        steady,
    );
    for (i, (&a, &b)) in l.iter().zip(r.iter()).enumerate() {
        assert!(
            a.is_finite() && b.is_finite(),
            "non-finite under bend / mod-wheel at sample {i}: L={a} R={b}"
        );
    }
}

// ── 6. Filter latency reporting (ticket 0086) ───────────────────────────────

/// The CLAP latency extension reports 0 with the filter off (the render path
/// is the unchanged sample-major bypass) and the halfband interp+decimate
/// round-trip group delay — derived in `vxn2_dsp::halfband` — at each
/// oversample factor when on. Filter params are pushed through the host's
/// main-thread (inactive) param flush, exactly the structural-edit path PDC
/// re-reads `get()` after.
#[test]
fn latency_extension_reports_filter_group_delay() {
    let entry = load_entry();
    let mut instance = instantiate(&entry);

    let enable = id_of("filter-enable").expect("filter-enable");
    let os = id_of("filter-oversample").expect("filter-oversample");

    // Push one param edit via the inactive main-thread flush.
    let set = |instance: &mut PluginInstance<TestHost>, id: usize, value: f64| {
        let params = instance
            .plugin_handle()
            .get_extension::<PluginParams>()
            .expect("params extension");
        let mut buf = EventBuffer::with_capacity(1);
        buf.push(&param_event(0, id, value));
        let mut out = EventBuffer::with_capacity(0);
        let mut inactive = instance
            .inactive_plugin_handle()
            .expect("plugin is inactive");
        params.flush(&mut inactive, &buf.as_input(), &mut out.as_output());
    };

    let latency = |instance: &mut PluginInstance<TestHost>| -> u32 {
        let mut handle = instance.plugin_handle();
        let ext = handle
            .get_extension::<PluginLatency>()
            .expect("latency extension");
        ext.get(&mut handle)
    };

    // Filter off by default → no added latency.
    assert_eq!(latency(&mut instance), 0, "filter off");

    // Enabled: enum index → factor 1/2/4/8 → round-trip base-rate latency.
    set(&mut instance, enable, 1.0);
    for (idx, want) in [(0u32, 0u32), (1, 16), (2, 24), (3, 28)] {
        set(&mut instance, os, idx as f64);
        assert_eq!(
            latency(&mut instance),
            want,
            "filter on, oversample idx {idx}"
        );
    }

    // Disabling returns to 0 even with the oversample selector left at 8×.
    set(&mut instance, enable, 0.0);
    assert_eq!(latency(&mut instance), 0, "filter off again");
}
