schema = 1

[meta]
name = "..GOTCHA.."
author = "Vulpus Labs"
category = "Synth"
comment = "Translated from DX7 factory ROM '..GOTCHA..': algo 8, feedback 7."

[params]
algo = 8
feedback = 4.9

# op1
op1-num = 1
op1-denom = 2
op1-level = 99
op1-vel-sens = 1
op1-eg-r1 = 99
op1-eg-r2 = 53
op1-eg-r3 = 85
op1-eg-r4 = 49
op1-eg-l1 = 99
op1-eg-l2 = 99
op1-eg-l3 = 85
op1-eg-l4 = 0
op1-ks-rate = 0
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 3
op2-detune = 2
op2-level = 99
op2-vel-sens = 2
op2-eg-r1 = 22
op2-eg-r2 = 99
op2-eg-r3 = 42
op2-eg-r4 = 35
op2-eg-l1 = 99
op2-eg-l2 = 32
op2-eg-l3 = 89
op2-eg-l4 = 0
op2-ks-rate = 0
op2-ks-l-depth = 0
op2-ks-r-depth = 0

# op3
op3-num = 1
op3-denom = 2
op3-level = 99
op3-vel-sens = 1
op3-eg-r1 = 36
op3-eg-r2 = 53
op3-eg-r3 = 20
op3-eg-r4 = 53
op3-eg-l1 = 99
op3-eg-l2 = 99
op3-eg-l3 = 0
op3-eg-l4 = 0
op3-ks-rate = 0
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 2
op4-fine = 22
op4-level = 99
op4-vel-sens = 2
op4-eg-r1 = 34
op4-eg-r2 = 99
op4-eg-r3 = 20
op4-eg-r4 = 27
op4-eg-l1 = 99
op4-eg-l2 = 33
op4-eg-l3 = 0
op4-eg-l4 = 0
op4-ks-rate = 0
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 1
op5-denom = 2
op5-detune = 1
op5-level = 99
op5-vel-sens = 2
op5-eg-r1 = 19
op5-eg-r2 = 79
op5-eg-r3 = 20
op5-eg-r4 = 40
op5-eg-l1 = 99
op5-eg-l2 = 97
op5-eg-l3 = 87
op5-eg-l4 = 0
op5-ks-rate = 3
op5-ks-l-depth = 0
op5-ks-r-depth = 0

# op6
op6-num = 1
op6-denom = 2
op6-level = 99
op6-vel-sens = 2
op6-eg-r1 = 14
op6-eg-r2 = 99
op6-eg-r3 = 20
op6-eg-r4 = 30
op6-eg-l1 = 99
op6-eg-l2 = 99
op6-eg-l3 = 0
op6-eg-l4 = 0
op6-ks-l-depth = 0
op6-ks-r-depth = 0

peg-r1 = 29
peg-r2 = 98
peg-r3 = 92
peg-r4 = 53
peg-l1 = 12
peg-l2 = 90
peg-l3 = -10
peg-l4 = 66

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -9.02
