schema = 1

[meta]
name = "Flexatone"
author = "Vulpus Labs"
category = "Synth"
comment = "Translated from DX7 factory ROM 'FLEXATONE': algo 7, feedback 6."

[params]
algo = 7
feedback = 4.2

# op1
op1-num = 3
op1-level = 99
op1-vel-sens = 4
op1-eg-r1 = 99
op1-eg-r2 = 66
op1-eg-r3 = 99
op1-eg-r4 = 99
op1-eg-l1 = 99
op1-eg-l2 = 0
op1-eg-l3 = 0
op1-eg-l4 = 0
op1-ks-rate = 0
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 5
op2-level = 71
op2-vel-sens = 0
op2-eg-r1 = 99
op2-eg-r2 = 89
op2-eg-r3 = 0
op2-eg-r4 = 0
op2-eg-l1 = 99
op2-eg-l2 = 0
op2-eg-l3 = 0
op2-eg-l4 = 0
op2-ks-rate = 0
op2-ks-l-depth = 0
op2-ks-r-depth = 0

# op3
op3-num = 2
op3-level = 99
op3-vel-sens = 1
op3-eg-r1 = 98
op3-eg-r2 = 47
op3-eg-r3 = 38
op3-eg-r4 = 37
op3-eg-l1 = 99
op3-eg-l2 = 0
op3-eg-l3 = 0
op3-eg-l4 = 0
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 7
op4-level = 50
op4-vel-sens = 0
op4-eg-r1 = 99
op4-eg-r2 = 34
op4-eg-r3 = 38
op4-eg-r4 = 28
op4-eg-l1 = 99
op4-eg-l2 = 0
op4-eg-l3 = 0
op4-eg-l4 = 0
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 20
op5-detune = 3
op5-level = 68
op5-vel-sens = 0
op5-eg-r1 = 85
op5-eg-r2 = 67
op5-eg-r3 = 96
op5-eg-r4 = 25
op5-eg-l1 = 99
op5-eg-l2 = 0
op5-eg-l3 = 0
op5-eg-l4 = 0
op5-ks-rate = 1
op5-ks-l-depth = 0
op5-ks-r-depth = 0

# op6
op6-num = 15
op6-detune = 9
op6-level = 86
op6-vel-sens = 0
op6-eg-r1 = 99
op6-eg-r2 = 79
op6-eg-r3 = 92
op6-eg-r4 = 71
op6-eg-l1 = 99
op6-eg-l2 = 0
op6-eg-l3 = 0
op6-eg-l4 = 0
op6-ks-rate = 3
op6-ks-break-pt = 36
op6-ks-l-depth = 0
op6-ks-r-depth = 96
op6-ks-r-curve = "neg-exp"

lfo2-shape = "Sine"
lfo2-rate = 8.87
lfo2-fade = 0.0

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -13.79

[[matrix]]
slot = 0
source = "lfo2"
dest = "global-pitch"
depth = 0.3636
