schema = 1

[meta]
name = "FRETLESS 2"
author = "Vulpus Labs"
category = "Synth"
comment = "Translated from DX7 factory ROM 'FRETLESS 2': algo 17, feedback 7. DX7 transpose -12 st baked into ratios."

[params]
algo = 17
feedback = 4.9

# op1
op1-num = 1
op1-fine = -75
op1-detune = 17
op1-level = 99
op1-vel-sens = 2
op1-eg-r1 = 75
op1-eg-r2 = 37
op1-eg-r3 = 18
op1-eg-r4 = 63
op1-eg-l1 = 99
op1-eg-l2 = 70
op1-eg-l3 = 0
op1-eg-l4 = 0
op1-ks-rate = 3
op1-ks-break-pt = 69
op1-ks-l-depth = 0
op1-ks-r-depth = 32
op1-ks-r-curve = "neg-lin"

# op2
op2-num = 1
op2-denom = 4
op2-fine = 3
op2-level = 80
op2-vel-sens = 2
op2-eg-r1 = 28
op2-eg-r2 = 37
op2-eg-r3 = 42
op2-eg-r4 = 50
op2-eg-l1 = 99
op2-eg-l2 = 0
op2-eg-l3 = 0
op2-eg-l4 = 0
op2-ks-rate = 1
op2-ks-break-pt = 62
op2-ks-l-depth = 0
op2-ks-r-depth = 35
op2-ks-r-curve = "neg-lin"

# op3
op3-num = 2
op3-fine = -50
op3-detune = 5
op3-level = 66
op3-vel-sens = 4
op3-eg-r1 = 73
op3-eg-r2 = 25
op3-eg-r3 = 32
op3-eg-r4 = 30
op3-eg-l1 = 97
op3-eg-l2 = 78
op3-eg-l3 = 0
op3-eg-l4 = 0
op3-ks-rate = 3
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 1
op4-fine = -75
op4-level = 99
op4-vel-sens = 2
op4-eg-r1 = 80
op4-eg-r2 = 39
op4-eg-r3 = 28
op4-eg-r4 = 53
op4-eg-l1 = 93
op4-eg-l2 = 57
op4-eg-l3 = 0
op4-eg-l4 = 0
op4-ks-rate = 3
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 1
op5-fine = -50
op5-detune = 17
op5-level = 75
op5-vel-sens = 2
op5-eg-r1 = 99
op5-eg-r2 = 51
op5-eg-r3 = 0
op5-eg-r4 = 0
op5-eg-l1 = 99
op5-eg-l2 = 74
op5-eg-l3 = 0
op5-eg-l4 = 0
op5-ks-rate = 4
op5-ks-break-pt = 55
op5-ks-l-depth = 0
op5-ks-r-depth = 32
op5-ks-r-curve = "neg-lin"

# op6
op6-num = 1
op6-fine = -75
op6-detune = 1
op6-level = 87
op6-vel-sens = 7
op6-eg-r1 = 25
op6-eg-r2 = 50
op6-eg-r3 = 24
op6-eg-r4 = 55
op6-eg-l1 = 96
op6-eg-l2 = 97
op6-eg-l3 = 0
op6-eg-l4 = 0
op6-ks-rate = 3
op6-ks-l-depth = 0
op6-ks-r-depth = 0

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -8.0
