schema = 1

[meta]
name = "HEAVYMETAL"
author = "Vulpus Labs"
category = "Synth"
comment = "Translated from DX7 factory ROM 'HEAVYMETAL': algo 14, feedback 2."

[params]
algo = 14
feedback = 1.4

# op1
op1-num = 1
op1-fine = -50
op1-detune = 1
op1-level = 95
op1-vel-sens = 0
op1-eg-r1 = 99
op1-eg-r2 = 0
op1-eg-r3 = 12
op1-eg-r4 = 70
op1-eg-l1 = 99
op1-eg-l2 = 99
op1-eg-l3 = 99
op1-eg-l4 = 0
op1-ks-rate = 1
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 1
op2-fine = -50
op2-detune = 3
op2-level = 90
op2-vel-sens = 0
op2-eg-r1 = 99
op2-eg-r2 = 31
op2-eg-r3 = 0
op2-eg-r4 = 0
op2-eg-l1 = 99
op2-eg-l2 = 0
op2-eg-l3 = 0
op2-eg-l4 = 0
op2-ks-rate = 0
op2-ks-l-depth = 0
op2-ks-r-depth = 0

# op3
op3-num = 1
op3-fine = -50
op3-level = 95
op3-vel-sens = 0
op3-eg-r1 = 87
op3-eg-r2 = 77
op3-eg-r3 = 79
op3-eg-r4 = 33
op3-eg-l1 = 41
op3-eg-l2 = 98
op3-eg-l3 = 90
op3-eg-l4 = 0
op3-ks-rate = 3
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 2
op4-detune = -1
op4-level = 76
op4-vel-sens = 0
op4-eg-r1 = 99
op4-eg-r2 = 49
op4-eg-r3 = 99
op4-eg-r4 = 44
op4-eg-l1 = 99
op4-eg-l2 = 83
op4-eg-l3 = 98
op4-eg-l4 = 0
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 1
op5-fine = -50
op5-detune = -1
op5-level = 99
op5-vel-sens = 0
op5-eg-r1 = 87
op5-eg-r2 = 77
op5-eg-r3 = 79
op5-eg-r4 = 33
op5-eg-l1 = 41
op5-eg-l2 = 98
op5-eg-l3 = 90
op5-eg-l4 = 0
op5-ks-rate = 5
op5-ks-l-depth = 0
op5-ks-r-depth = 0

# op6
op6-num = 3
op6-detune = 4
op6-level = 92
op6-vel-sens = 0
op6-eg-r1 = 98
op6-eg-r2 = 49
op6-eg-r3 = 98
op6-eg-r4 = 44
op6-eg-l1 = 99
op6-eg-l2 = 83
op6-eg-l3 = 98
op6-eg-l4 = 0
op6-ks-break-pt = 53
op6-ks-l-depth = 99
op6-ks-r-depth = 19
op6-ks-l-curve = "neg-exp"
op6-ks-r-curve = "neg-lin"

lfo2-shape = "Tri"
lfo2-rate = 5.22
lfo2-delay = 720.0
lfo2-fade = 0.0

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -10.2

[[matrix]]
slot = 0
source = "lfo2"
dest = "global-pitch"
depth = 0.0087
