schema = 1

[meta]
name = "HONKY TONK"
author = "Vulpus Labs"
category = "Synth"
comment = "Translated from DX7 factory ROM 'HONKY TONK': algo 3, feedback 4."

[params]
algo = 3
feedback = 2.8

# op1
op1-num = 1
op1-detune = 4
op1-level = 91
op1-vel-sens = 4
op1-eg-r1 = 90
op1-eg-r2 = 30
op1-eg-r3 = 28
op1-eg-r4 = 50
op1-eg-l1 = 99
op1-eg-l2 = 95
op1-eg-l3 = 0
op1-eg-l4 = 0
op1-ks-rate = 3
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 1
op2-detune = -5
op2-level = 81
op2-vel-sens = 2
op2-eg-r1 = 98
op2-eg-r2 = 36
op2-eg-r3 = 6
op2-eg-r4 = 32
op2-eg-l1 = 91
op2-eg-l2 = 90
op2-eg-l3 = 0
op2-eg-l4 = 0
op2-ks-break-pt = 71
op2-ks-l-depth = 22
op2-ks-r-depth = 50
op2-ks-l-curve = "pos-lin"
op2-ks-r-curve = "neg-lin"

# op3
op3-num = 7
op3-detune = 5
op3-level = 99
op3-vel-sens = 2
op3-eg-r1 = 94
op3-eg-r2 = 80
op3-eg-r3 = 19
op3-eg-r4 = 12
op3-eg-l1 = 83
op3-eg-l2 = 67
op3-eg-l3 = 0
op3-eg-l4 = 0
op3-ks-rate = 3
op3-ks-break-pt = 64
op3-ks-l-depth = 9
op3-ks-r-depth = 20
op3-ks-l-curve = "pos-lin"
op3-ks-r-curve = "neg-lin"

# op4
op4-num = 1
op4-detune = 5
op4-level = 95
op4-vel-sens = 3
op4-eg-r1 = 90
op4-eg-r2 = 64
op4-eg-r3 = 28
op4-eg-r4 = 48
op4-eg-l1 = 99
op4-eg-l2 = 97
op4-eg-l3 = 0
op4-eg-l4 = 0
op4-ks-rate = 3
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 1
op5-detune = -5
op5-level = 87
op5-vel-sens = 2
op5-eg-r1 = 98
op5-eg-r2 = 20
op5-eg-r3 = 6
op5-eg-r4 = 2
op5-eg-l1 = 91
op5-eg-l2 = 90
op5-eg-l3 = 0
op5-eg-l4 = 0
op5-ks-break-pt = 62
op5-ks-l-depth = 0
op5-ks-r-depth = 27
op5-ks-r-curve = "neg-lin"

# op6
op6-num = 5
op6-detune = 1
op6-level = 96
op6-vel-sens = 2
op6-eg-r1 = 94
op6-eg-r2 = 1
op6-eg-r3 = 33
op6-eg-r4 = 12
op6-eg-l1 = 4
op6-eg-l2 = 19
op6-eg-l3 = 0
op6-eg-l4 = 0
op6-ks-l-depth = 0
op6-ks-r-depth = 0

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -10.2
