schema = 1

[meta]
name = "WATER GDN"
author = "Vulpus Labs"
category = "Synth"
comment = "Translated from DX7 factory ROM 'WATER GDN': algo 32, feedback 3."

[params]
algo = 32
feedback = 2.1

# op1
op1-num = 1
op1-level = 99
op1-vel-sens = 0
op1-eg-r1 = 99
op1-eg-r2 = 99
op1-eg-r3 = 60
op1-eg-r4 = 65
op1-eg-l1 = 0
op1-eg-l2 = 99
op1-eg-l3 = 0
op1-eg-l4 = 0
op1-ks-rate = 0
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 3
op2-denom = 2
op2-level = 99
op2-vel-sens = 0
op2-eg-r1 = 40
op2-eg-r2 = 99
op2-eg-r3 = 60
op2-eg-r4 = 72
op2-eg-l1 = 0
op2-eg-l2 = 99
op2-eg-l3 = 0
op2-eg-l4 = 0
op2-ks-rate = 0
op2-ks-l-depth = 0
op2-ks-r-depth = 0

# op3
op3-num = 2
op3-level = 99
op3-vel-sens = 0
op3-eg-r1 = 25
op3-eg-r2 = 99
op3-eg-r3 = 60
op3-eg-r4 = 77
op3-eg-l1 = 0
op3-eg-l2 = 99
op3-eg-l3 = 0
op3-eg-l4 = 0
op3-ks-rate = 0
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 3
op4-level = 95
op4-vel-sens = 0
op4-eg-r1 = 20
op4-eg-r2 = 99
op4-eg-r3 = 60
op4-eg-r4 = 80
op4-eg-l1 = 0
op4-eg-l2 = 99
op4-eg-l3 = 0
op4-eg-l4 = 0
op4-ks-rate = 0
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 6
op5-level = 93
op5-vel-sens = 0
op5-eg-r1 = 14
op5-eg-r2 = 99
op5-eg-r3 = 60
op5-eg-r4 = 80
op5-eg-l1 = 0
op5-eg-l2 = 99
op5-eg-l3 = 0
op5-eg-l4 = 0
op5-ks-rate = 0
op5-ks-l-depth = 0
op5-ks-r-depth = 0

# op6
op6-num = 12
op6-level = 99
op6-vel-sens = 0
op6-eg-r1 = 9
op6-eg-r2 = 99
op6-eg-r3 = 60
op6-eg-r4 = 81
op6-eg-l1 = 0
op6-eg-l2 = 99
op6-eg-l3 = 0
op6-eg-l4 = 0
op6-ks-rate = 0
op6-ks-l-depth = 0
op6-ks-r-depth = 0

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -19.0
