schema = 1

[meta]
name = "BASSOON"
author = "Vulpus Labs"
category = "Bass"
comment = "Translated from DX7 factory ROM 'BASSOON': algo 2, feedback 3. DX7 transpose -12 st baked into ratios."

[params]
algo = 2
feedback = 2.1

# op1
op1-num = 1
op1-level = 99
op1-vel-sens = 3
op1-eg-r1 = 60
op1-eg-r2 = 45
op1-eg-r3 = 27
op1-eg-r4 = 70
op1-eg-l1 = 99
op1-eg-l2 = 95
op1-eg-l3 = 85
op1-eg-l4 = 0
op1-ks-rate = 3
op1-ks-break-pt = 38
op1-ks-l-depth = 0
op1-ks-r-depth = 21
op1-ks-r-curve = "neg-lin"

# op2
op2-num = 1
op2-denom = 4
op2-level = 78
op2-vel-sens = 0
op2-eg-r1 = 55
op2-eg-r2 = 0
op2-eg-r3 = 12
op2-eg-r4 = 70
op2-eg-l1 = 99
op2-eg-l2 = 90
op2-eg-l3 = 99
op2-eg-l4 = 0
op2-ks-rate = 1
op2-ks-l-depth = 0
op2-ks-r-depth = 0

# op3
op3-num = 1
op3-level = 99
op3-vel-sens = 1
op3-eg-r1 = 60
op3-eg-r2 = 45
op3-eg-r3 = 27
op3-eg-r4 = 70
op3-eg-l1 = 99
op3-eg-l2 = 95
op3-eg-l3 = 85
op3-eg-l4 = 0
op3-ks-rate = 3
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 1
op4-denom = 4
op4-level = 72
op4-vel-sens = 1
op4-eg-r1 = 55
op4-eg-r2 = 0
op4-eg-r3 = 12
op4-eg-r4 = 70
op4-eg-l1 = 99
op4-eg-l2 = 90
op4-eg-l3 = 99
op4-eg-l4 = 0
op4-ks-rate = 1
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 5
op5-denom = 2
op5-level = 79
op5-vel-sens = 0
op5-eg-r1 = 97
op5-eg-r2 = 80
op5-eg-r3 = 80
op5-eg-r4 = 70
op5-eg-l1 = 99
op5-eg-l2 = 90
op5-eg-l3 = 70
op5-eg-l4 = 0
op5-ks-rate = 1
op5-ks-l-depth = 0
op5-ks-r-depth = 0

# op6
op6-num = 3
op6-detune = 4
op6-level = 66
op6-vel-sens = 0
op6-eg-r1 = 55
op6-eg-r2 = 45
op6-eg-r3 = 27
op6-eg-r4 = 70
op6-eg-l1 = 99
op6-eg-l2 = 95
op6-eg-l3 = 85
op6-eg-l4 = 0
op6-ks-rate = 3
op6-ks-break-pt = 61
op6-ks-l-depth = 10
op6-ks-r-depth = 62
op6-ks-l-curve = "pos-lin"
op6-ks-r-curve = "neg-lin"

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -10.2
