//! In-process integration smoke for vxn3-clap (ticket 0046).
//!
//! Drives the empty-vessel plugin through the real CLAP lifecycle via
//! clack-host (`init` → `activate(44.1k / 256)` → `start_processing` →
//! `process`) and asserts it loads, reports a stereo output port, and renders
//! finite silence — with and without a host transport. This is the automated
//! stand-in for "loads in a CLAP host without errors": if it passes, the entry,
//! factory, descriptor, audio-port, and process wiring are correct end-to-end.
//!
//! Loads via the in-process `rlib` target so panics surface with real
//! backtraces; nothing here goes through `dlopen`.

use clack_host::events::event_types::{TransportEvent, TransportFlags};
use clack_host::events::{EventFlags, EventHeader};
use clack_host::factory::plugin::PluginFactory;
use clack_host::prelude::*;
use clack_host::utils::{BeatTime, SecondsTime};
use clack_plugin::clack_entry;
use clack_plugin::prelude::{EntryDescriptor, SinglePluginEntry};
use vxn3_clap::VxnPlugin;

static VXN_ENTRY: EntryDescriptor = clack_entry!(SinglePluginEntry<VxnPlugin>);

const SAMPLE_RATE: f64 = 44_100.0;
const MAX_FRAMES: u32 = 256;
const PLUGIN_ID: &core::ffi::CStr = c"labs.vulpus.vxn3";

// ── Host stub ────────────────────────────────────────────────────────────────

struct TestHostShared;
impl SharedHandler<'_> for TestHostShared {
    fn request_restart(&self) {}
    fn request_process(&self) {}
    fn request_callback(&self) {}
}

struct TestHost;
impl HostHandlers for TestHost {
    type Shared<'a> = TestHostShared;
    type MainThread<'a> = ();
    type AudioProcessor<'a> = ();
}

fn load_entry() -> PluginEntry {
    // SAFETY: VXN_ENTRY is generated by clack's own macro.
    unsafe { PluginEntry::load_from_raw(&VXN_ENTRY, c"/tmp/VXN3.clap") }.unwrap()
}

fn host_info() -> HostInfo {
    HostInfo::new("VXN3 Smoke", "Vulpus Labs", "https://vulpus.labs", "0.0.0").unwrap()
}

fn instantiate(entry: &PluginEntry) -> PluginInstance<TestHost> {
    PluginInstance::<TestHost>::new(|_| TestHostShared, |_| (), entry, PLUGIN_ID, &host_info())
        .expect("instantiation failed")
}

fn activate_started(
    instance: &mut PluginInstance<TestHost>,
) -> StartedPluginAudioProcessor<TestHost> {
    let cfg = PluginAudioConfiguration {
        sample_rate: SAMPLE_RATE,
        min_frames_count: 1,
        max_frames_count: MAX_FRAMES,
    };
    instance
        .activate(|_, _| (), cfg)
        .expect("activation failed")
        .start_processing()
        .expect("start_processing failed")
}

/// Drive one `process()` call into a stereo f32 output port (the synth has no
/// audio inputs). Returns nothing — the assertions live in the callers.
fn process_one(
    processor: &mut StartedPluginAudioProcessor<TestHost>,
    transport: Option<&TransportEvent>,
    out_l: &mut [f32],
    out_r: &mut [f32],
    steady_time: u64,
) {
    let in_events = EventBuffer::with_capacity(0);
    let mut out_events = EventBuffer::with_capacity(0);
    let inputs = InputAudioBuffers::empty();
    let mut output_ports = AudioPorts::with_capacity(2, 1);
    let chans: [&mut [f32]; 2] = [out_l, out_r];
    let mut outputs = output_ports.with_output_buffers([AudioPortBuffer {
        channels: AudioPortBufferType::f32_output_only(chans.into_iter()),
        latency: 0,
    }]);
    processor
        .process(
            &inputs,
            &mut outputs,
            &in_events.as_input(),
            &mut out_events.as_output(),
            Some(steady_time),
            transport,
        )
        .expect("process failed");
}

/// A transport event with tempo, play-state, and a beats timeline set — the
/// full clock 0046 surfaces to the engine.
fn playing_transport(bpm: f64, beats: i64) -> TransportEvent {
    TransportEvent {
        header: EventHeader::new_core(0, EventFlags::empty()),
        flags: TransportFlags::HAS_TEMPO
            | TransportFlags::IS_PLAYING
            | TransportFlags::HAS_BEATS_TIMELINE,
        song_pos_beats: BeatTime::from_int(beats),
        song_pos_seconds: SecondsTime::from_int(0),
        tempo: bpm,
        tempo_inc: 0.0,
        loop_start_beats: BeatTime::from_int(0),
        loop_end_beats: BeatTime::from_int(0),
        loop_start_seconds: SecondsTime::from_int(0),
        loop_end_seconds: SecondsTime::from_int(0),
        bar_start: BeatTime::from_int(0),
        bar_number: 0,
        time_signature_numerator: 4,
        time_signature_denominator: 4,
    }
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[test]
fn entry_loads_and_describes_vxn3() {
    let entry = load_entry();
    let factory = entry.get_factory::<PluginFactory>().unwrap();
    assert_eq!(factory.plugin_count(), 1);
    let desc = factory.plugin_descriptor(0).unwrap();
    assert_eq!(desc.id().unwrap().to_str().unwrap(), "labs.vulpus.vxn3");
    assert_eq!(desc.name().unwrap().to_str().unwrap(), "VXN3");
}

#[test]
fn renders_silence_without_transport() {
    let entry = load_entry();
    let mut instance = instantiate(&entry);
    let mut processor = activate_started(&mut instance);

    let mut steady = 0u64;
    for _ in 0..8 {
        let mut l = vec![1.0_f32; MAX_FRAMES as usize];
        let mut r = vec![-1.0_f32; MAX_FRAMES as usize];
        process_one(&mut processor, None, &mut l, &mut r, steady);
        steady += MAX_FRAMES as u64;
        assert!(
            l.iter().chain(r.iter()).all(|&v| v == 0.0),
            "expected silence with no transport"
        );
    }
}

#[test]
fn renders_silence_under_running_transport() {
    let entry = load_entry();
    let mut instance = instantiate(&entry);
    let mut processor = activate_started(&mut instance);

    // 174 BPM, rolling, advancing the beat clock each block. Empty vessel: the
    // engine consumes the transport but still renders finite silence.
    let mut steady = 0u64;
    for block in 0..8 {
        let t = playing_transport(174.0, block);
        let mut l = vec![0.5_f32; MAX_FRAMES as usize];
        let mut r = vec![0.5_f32; MAX_FRAMES as usize];
        process_one(&mut processor, Some(&t), &mut l, &mut r, steady);
        steady += MAX_FRAMES as u64;
        for &v in l.iter().chain(r.iter()) {
            assert!(v.is_finite(), "non-finite under transport: {v}");
            assert_eq!(v, 0.0, "expected silence under transport");
        }
    }
}
