schema = 1

[meta]
name = "STRINGS 3"
author = "Vulpus Labs"
category = "Strings"
comment = "Translated from DX7 factory ROM 'STRINGS 3': algo 15, feedback 7. DX7 transpose -12 st baked into ratios."

[params]
algo = 15
feedback = 4.9

# op1
op1-num = 1
op1-fine = -50
op1-level = 99
op1-vel-sens = 1
op1-eg-r1 = 52
op1-eg-r2 = 30
op1-eg-r3 = 25
op1-eg-r4 = 43
op1-eg-l1 = 99
op1-eg-l2 = 92
op1-eg-l3 = 90
op1-eg-l4 = 0
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 1
op2-fine = -50
op2-level = 86
op2-vel-sens = 0
op2-eg-r1 = 99
op2-eg-r2 = 71
op2-eg-r3 = 35
op2-eg-r4 = 51
op2-eg-l1 = 82
op2-eg-l2 = 92
op2-eg-l3 = 87
op2-eg-l4 = 0
op2-ks-rate = 1
op2-ks-l-depth = 0
op2-ks-r-depth = 0

# op3
op3-num = 1
op3-fine = -50
op3-level = 99
op3-vel-sens = 1
op3-eg-r1 = 50
op3-eg-r2 = 52
op3-eg-r3 = 35
op3-eg-r4 = 41
op3-eg-l1 = 99
op3-eg-l2 = 92
op3-eg-l3 = 91
op3-eg-l4 = 0
op3-ks-break-pt = 72
op3-ks-l-depth = 98
op3-ks-r-depth = 60
op3-ks-l-curve = "pos-lin"
op3-ks-r-curve = "neg-lin"

# op4
op4-num = 1
op4-fine = -50
op4-level = 75
op4-vel-sens = 2
op4-eg-r1 = 96
op4-eg-r2 = 19
op4-eg-r3 = 20
op4-eg-r4 = 54
op4-eg-l1 = 99
op4-eg-l2 = 92
op4-eg-l3 = 89
op4-eg-l4 = 0
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 2
op5-fine = -50
op5-level = 84
op5-vel-sens = 1
op5-eg-r1 = 53
op5-eg-r2 = 67
op5-eg-r3 = 38
op5-eg-r4 = 54
op5-eg-l1 = 86
op5-eg-l2 = 92
op5-eg-l3 = 74
op5-eg-l4 = 0
op5-ks-l-depth = 0
op5-ks-r-depth = 0

# op6
op6-num = 7
op6-level = 54
op6-vel-sens = 2
op6-eg-r1 = 53
op6-eg-r2 = 64
op6-eg-r3 = 44
op6-eg-r4 = 54
op6-eg-l1 = 99
op6-eg-l2 = 92
op6-eg-l3 = 56
op6-eg-l4 = 0
op6-ks-break-pt = 76
op6-ks-l-depth = 25
op6-ks-r-depth = 0
op6-ks-l-curve = "pos-lin"

lfo2-shape = "Sine"
lfo2-rate = 3.76
lfo2-delay = 864.0
lfo2-fade = 0.0

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -10.2

[[matrix]]
slot = 0
source = "lfo2"
dest = "global-pitch"
depth = 0.0119
