schema = 1

[meta]
name = "VIBE 2"
author = "Vulpus Labs"
category = "Mallet"
comment = "Translated from DX7 factory ROM 'VIBE    2': algo 5, feedback 2."

[params]
algo = 5
feedback = 1.4

# op1
op1-num = 1
op1-detune = -5
op1-level = 99
op1-vel-sens = 0
op1-eg-r1 = 80
op1-eg-r2 = 85
op1-eg-r3 = 24
op1-eg-r4 = 42
op1-eg-l1 = 99
op1-eg-l2 = 90
op1-eg-l3 = 0
op1-eg-l4 = 0
op1-ks-rate = 3
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 5
op2-level = 49
op2-vel-sens = 0
op2-eg-r1 = 49
op2-eg-r2 = 85
op2-eg-r3 = 24
op2-eg-r4 = 42
op2-eg-l1 = 99
op2-eg-l2 = 90
op2-eg-l3 = 0
op2-eg-l4 = 0
op2-ks-rate = 3
op2-ks-l-depth = 0
op2-ks-r-depth = 0

# op3
op3-num = 1
op3-detune = 5
op3-level = 99
op3-vel-sens = 2
op3-eg-r1 = 80
op3-eg-r2 = 85
op3-eg-r3 = 24
op3-eg-r4 = 42
op3-eg-l1 = 99
op3-eg-l2 = 90
op3-eg-l3 = 0
op3-eg-l4 = 0
op3-ks-rate = 3
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 10
op4-fine = -13
op4-detune = -1
op4-level = 52
op4-vel-sens = 5
op4-eg-r1 = 48
op4-eg-r2 = 85
op4-eg-r3 = 24
op4-eg-r4 = 42
op4-eg-l1 = 99
op4-eg-l2 = 90
op4-eg-l3 = 0
op4-eg-l4 = 0
op4-ks-rate = 3
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 4
op5-fine = -2
op5-detune = 5
op5-level = 83
op5-vel-sens = 3
op5-eg-r1 = 95
op5-eg-r2 = 57
op5-eg-r3 = 99
op5-eg-r4 = 50
op5-eg-l1 = 99
op5-eg-l2 = 32
op5-eg-l3 = 0
op5-eg-l4 = 0
op5-ks-rate = 5
op5-ks-break-pt = 60
op5-ks-l-depth = 12
op5-ks-r-depth = 12
op5-ks-r-curve = "pos-lin"

# op6
op6-num = 9
op6-detune = 10
op6-level = 89
op6-vel-sens = 4
op6-eg-r1 = 85
op6-eg-r2 = 34
op6-eg-r3 = 31
op6-eg-r4 = 50
op6-eg-l1 = 99
op6-eg-l2 = 51
op6-eg-l3 = 0
op6-eg-l4 = 0
op6-ks-rate = 5
op6-ks-break-pt = 60
op6-ks-l-depth = 12
op6-ks-r-depth = 12
op6-ks-r-curve = "pos-lin"

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -12.4
