schema = 1

[meta]
name = "Vibraphone 1"
author = "Vulpus Labs"
category = "Mallet"
comment = "Translated from DX7 factory ROM 'VIBE    1': algo 23, feedback 5."

[params]
algo = 23
feedback = 3.5

# op1
op1-num = 4
op1-level = 50
op1-vel-sens = 7
op1-eg-r1 = 99
op1-eg-r2 = 28
op1-eg-r3 = 99
op1-eg-r4 = 50
op1-eg-l1 = 99
op1-eg-l2 = 25
op1-eg-l3 = 0
op1-eg-l4 = 0
op1-ks-break-pt = 60
op1-ks-l-depth = 12
op1-ks-r-depth = 12
op1-ks-r-curve = "pos-lin"

# op2
op2-num = 1
op2-level = 99
op2-vel-sens = 1
op2-eg-r1 = 80
op2-eg-r2 = 85
op2-eg-r3 = 24
op2-eg-r4 = 50
op2-eg-l1 = 99
op2-eg-l2 = 90
op2-eg-l3 = 0
op2-eg-l4 = 0
op2-ks-break-pt = 60
op2-ks-l-depth = 4
op2-ks-r-depth = 12
op2-ks-r-curve = "pos-lin"

# op3
op3-num = 3
op3-level = 72
op3-vel-sens = 4
op3-eg-r1 = 80
op3-eg-r2 = 85
op3-eg-r3 = 43
op3-eg-r4 = 50
op3-eg-l1 = 99
op3-eg-l2 = 74
op3-eg-l3 = 0
op3-eg-l4 = 0
op3-ks-rate = 4
op3-ks-break-pt = 60
op3-ks-l-depth = 12
op3-ks-r-depth = 12
op3-ks-r-curve = "pos-lin"

# op4
op4-num = 1
op4-detune = -5
op4-level = 99
op4-vel-sens = 1
op4-eg-r1 = 80
op4-eg-r2 = 85
op4-eg-r3 = 24
op4-eg-r4 = 50
op4-eg-l1 = 99
op4-eg-l2 = 90
op4-eg-l3 = 0
op4-eg-l4 = 0
op4-ks-rate = 3
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 1
op5-detune = 5
op5-level = 99
op5-vel-sens = 5
op5-eg-r1 = 80
op5-eg-r2 = 85
op5-eg-r3 = 24
op5-eg-r4 = 50
op5-eg-l1 = 99
op5-eg-l2 = 90
op5-eg-l3 = 42
op5-eg-l4 = 0
op5-ks-rate = 3
op5-ks-l-depth = 0
op5-ks-r-depth = 0

# op6
op6-num = 14
op6-level = 57
op6-vel-sens = 7
op6-eg-r1 = 99
op6-eg-r2 = 48
op6-eg-r3 = 99
op6-eg-r4 = 50
op6-eg-l1 = 99
op6-eg-l2 = 32
op6-eg-l3 = 0
op6-eg-l4 = 0
op6-ks-rate = 5
op6-ks-break-pt = 60
op6-ks-l-depth = 12
op6-ks-r-depth = 12
op6-ks-r-curve = "pos-lin"

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -16.87
