schema = 1

[meta]
name = "XYLOPHONE"
author = "Vulpus Labs"
category = "Mallet"
comment = "Translated from DX7 factory ROM 'XYLOPHONE': algo 7, feedback 0. DX7 transpose +24 st baked into ratios."

[params]
algo = 7

# op1
op1-num = 2
op1-level = 99
op1-vel-sens = 5
op1-eg-r1 = 95
op1-eg-r2 = 43
op1-eg-r3 = 49
op1-eg-r4 = 53
op1-eg-l1 = 99
op1-eg-l2 = 92
op1-eg-l3 = 0
op1-eg-l4 = 0
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 12
op2-level = 99
op2-vel-sens = 2
op2-eg-r1 = 99
op2-eg-r2 = 71
op2-eg-r3 = 0
op2-eg-r4 = 0
op2-eg-l1 = 82
op2-eg-l2 = 48
op2-eg-l3 = 0
op2-eg-l4 = 0
op2-ks-rate = 0
op2-ks-break-pt = 75
op2-ks-l-depth = 0
op2-ks-r-depth = 46
op2-ks-r-curve = "neg-lin"

# op3
op3-num = 2
op3-level = 99
op3-vel-sens = 6
op3-eg-r1 = 95
op3-eg-r2 = 50
op3-eg-r3 = 49
op3-eg-r4 = 41
op3-eg-l1 = 99
op3-eg-l2 = 92
op3-eg-l3 = 0
op3-eg-l4 = 0
op3-ks-rate = 3
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 12
op4-level = 94
op4-vel-sens = 2
op4-eg-r1 = 99
op4-eg-r2 = 73
op4-eg-r3 = 0
op4-eg-r4 = 14
op4-eg-l1 = 82
op4-eg-l2 = 48
op4-eg-l3 = 0
op4-eg-l4 = 0
op4-ks-rate = 0
op4-ks-break-pt = 75
op4-ks-l-depth = 0
op4-ks-r-depth = 46
op4-ks-r-curve = "neg-lin"

# op5
op5-num = 2
op5-level = 79
op5-vel-sens = 2
op5-eg-r1 = 99
op5-eg-r2 = 86
op5-eg-r3 = 55
op5-eg-r4 = 0
op5-eg-l1 = 96
op5-eg-l2 = 78
op5-eg-l3 = 0
op5-eg-l4 = 0
op5-ks-rate = 0
op5-ks-l-depth = 0
op5-ks-r-depth = 0

# op6
op6-num = 16
op6-level = 75
op6-vel-sens = 5
op6-eg-r1 = 0
op6-eg-r2 = 81
op6-eg-r3 = 55
op6-eg-r4 = 0
op6-eg-l1 = 78
op6-eg-l2 = 78
op6-eg-l3 = 0
op6-eg-l4 = 0
op6-ks-rate = 0
op6-ks-l-depth = 0
op6-ks-r-depth = 0

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -9.02
