schema = 1

[meta]
name = "SYN-LEAD 2"
author = "Vulpus Labs"
category = "Lead"
comment = "Translated from DX7 factory ROM 'SYN-LEAD 2': algo 22, feedback 7."

[params]
algo = 22
feedback = 4.9

# op1
op1-num = 1
op1-level = 93
op1-vel-sens = 0
op1-eg-r1 = 99
op1-eg-r2 = 76
op1-eg-r3 = 99
op1-eg-r4 = 71
op1-eg-l1 = 99
op1-eg-l2 = 88
op1-eg-l3 = 96
op1-eg-l4 = 0
op1-ks-rate = 0
op1-ks-break-pt = 60
op1-ks-l-depth = 0
op1-ks-r-depth = 14
op1-ks-r-curve = "pos-lin"

# op2
op2-num = 2
op2-level = 78
op2-vel-sens = 0
op2-eg-r1 = 99
op2-eg-r2 = 42
op2-eg-r3 = 23
op2-eg-r4 = 71
op2-eg-l1 = 99
op2-eg-l2 = 56
op2-eg-l3 = 56
op2-eg-l4 = 0
op2-ks-rate = 0
op2-ks-break-pt = 48
op2-ks-l-depth = 0
op2-ks-r-depth = 45
op2-ks-r-curve = "neg-exp"

# op3
op3-num = 1
op3-level = 99
op3-vel-sens = 0
op3-eg-r1 = 99
op3-eg-r2 = 76
op3-eg-r3 = 99
op3-eg-r4 = 71
op3-eg-l1 = 99
op3-eg-l2 = 88
op3-eg-l3 = 96
op3-eg-l4 = 0
op3-ks-rate = 0
op3-ks-break-pt = 60
op3-ks-l-depth = 0
op3-ks-r-depth = 14
op3-ks-r-curve = "pos-lin"

# op4
op4-num = 1
op4-level = 99
op4-vel-sens = 0
op4-eg-r1 = 99
op4-eg-r2 = 76
op4-eg-r3 = 99
op4-eg-r4 = 71
op4-eg-l1 = 99
op4-eg-l2 = 88
op4-eg-l3 = 96
op4-eg-l4 = 0
op4-ks-rate = 0
op4-ks-break-pt = 60
op4-ks-l-depth = 0
op4-ks-r-depth = 14
op4-ks-r-curve = "pos-lin"

# op5
op5-num = 1
op5-level = 98
op5-vel-sens = 0
op5-eg-r1 = 99
op5-eg-r2 = 76
op5-eg-r3 = 99
op5-eg-r4 = 71
op5-eg-l1 = 99
op5-eg-l2 = 88
op5-eg-l3 = 96
op5-eg-l4 = 0
op5-ks-rate = 0
op5-ks-break-pt = 60
op5-ks-l-depth = 0
op5-ks-r-depth = 14
op5-ks-r-curve = "pos-lin"

# op6
op6-num = 2
op6-level = 76
op6-vel-sens = 0
op6-eg-r1 = 99
op6-eg-r2 = 42
op6-eg-r3 = 23
op6-eg-r4 = 71
op6-eg-l1 = 99
op6-eg-l2 = 56
op6-eg-l3 = 56
op6-eg-l4 = 0
op6-ks-rate = 0
op6-ks-break-pt = 48
op6-ks-l-depth = 0
op6-ks-r-depth = 45
op6-ks-r-curve = "neg-exp"

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -13.91
