schema = 1

[meta]
name = "WOOD BLOCK"
author = "Vulpus Labs"
category = "Perc"
comment = "Translated from DX7 factory ROM 'WOOD BLOCK': algo 18, feedback 7. DX7 transpose +12 st baked into ratios."

[params]
algo = 18
feedback = 4.9

# op1
op1-num = 2
op1-level = 97
op1-vel-sens = 3
op1-eg-r1 = 96
op1-eg-r2 = 34
op1-eg-r3 = 44
op1-eg-r4 = 66
op1-eg-l1 = 99
op1-eg-l2 = 90
op1-eg-l3 = 0
op1-eg-l4 = 0
op1-ks-rate = 6
op1-ks-l-depth = 0
op1-ks-r-depth = 0

# op2
op2-num = 10
op2-level = 79
op2-vel-sens = 1
op2-eg-r1 = 96
op2-eg-r2 = 93
op2-eg-r3 = 65
op2-eg-r4 = 66
op2-eg-l1 = 60
op2-eg-l2 = 90
op2-eg-l3 = 0
op2-eg-l4 = 0
op2-ks-rate = 5
op2-ks-break-pt = 71
op2-ks-l-depth = 0
op2-ks-r-depth = 23
op2-ks-r-curve = "neg-lin"

# op3
op3-num = 10
op3-level = 70
op3-vel-sens = 3
op3-eg-r1 = 96
op3-eg-r2 = 93
op3-eg-r3 = 80
op3-eg-r4 = 66
op3-eg-l1 = 99
op3-eg-l2 = 90
op3-eg-l3 = 0
op3-eg-l4 = 0
op3-ks-l-depth = 0
op3-ks-r-depth = 0

# op4
op4-num = 10
op4-level = 65
op4-vel-sens = 0
op4-eg-r1 = 96
op4-eg-r2 = 83
op4-eg-r3 = 67
op4-eg-r4 = 66
op4-eg-l1 = 99
op4-eg-l2 = 90
op4-eg-l3 = 0
op4-eg-l4 = 0
op4-ks-l-depth = 0
op4-ks-r-depth = 0

# op5
op5-num = 10
op5-level = 55
op5-vel-sens = 2
op5-eg-r1 = 96
op5-eg-r2 = 93
op5-eg-r3 = 49
op5-eg-r4 = 66
op5-eg-l1 = 99
op5-eg-l2 = 90
op5-eg-l3 = 0
op5-eg-l4 = 0
op5-ks-l-depth = 0
op5-ks-r-depth = 0

# op6
op6-num = 32
op6-fine = 99
op6-level = 79
op6-vel-sens = 3
op6-eg-r1 = 96
op6-eg-r2 = 83
op6-eg-r3 = 49
op6-eg-r4 = 66
op6-eg-l1 = 99
op6-eg-l2 = 90
op6-eg-l3 = 0
op6-eg-l4 = 0
op6-ks-l-depth = 0
op6-ks-r-depth = 0

stack-density = 1
delay-on = false
reverb-on = false
master-volume = -1.49
